### ISSUE TITLE
아이작 서바이벌 관련

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#10]
1. 경험치통 위치 아래로 변경 하기 (어디서 건드는지만 알려주면 내가 알아서 최적화 위치 찾겠음)
2. 멀리서 몬스터를 죽이더라도 동전이 사라지지 않게 변경
3. 30분 이후 등장하는 몬스터의 수 절반으로 줄이기

**Comment by pdom0327** [comment]
1. 1664, 1666, 1667, 1669, 1671번째 줄입니다.
    ```lua
    f:DrawString("exp :",X좌표,Y좌표,KColor(1,1,1,0.5,0,0,0),0,true)
    ```

2. 257 ~ 262번째 줄 제거
![image](https://github.com/TeamHY/Redrawn_Hard/assets/12953393/7a7d038f-ce69-4e67-addc-7c8f1dfa8a8d)

3. 점점 증가하는 방식인듯해서 절반을 어떻게 줄여할지 잘 모르겠어요.

**Comment by pdom0327** [comment]
[TeamHY/Survivors](https://github.com/TeamHY/Survivors)로 이전합니다.
