### ISSUE TITLE
챌린지 관련 리뉴얼 및 버그

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#104]
-챌린지가 정상적으로 깨지지 않으며, 메가 사탄 처치 시 에도 트로피가 나오지 않음
-챌린지 해금 상태가 아닐 경우 배열이 제거되는 시스템은 아예 삭제
-모든 챌린지가 깨져 있을 경우 아이템, 장신구, 카드 소환
-소환되는 아이템, 장신구, 카드는 밴 리스트처럼 언제든지 수정 가능하도록 변경
![KakaoTalk_20240111_145217312](https://github.com/TeamHY/Astrobirth/assets/28684443/e8e86032-80ce-490b-8ab7-a46910ab5de8)
![KakaoTalk_20240111_145327453](https://github.com/TeamHY/Astrobirth/assets/28684443/921473d5-4b57-4e80-bb4b-3af7be34aecf)
![KakaoTalk_20240111_145515696](https://github.com/TeamHY/Astrobirth/assets/28684443/69db5138-7690-4750-8f36-2813e3581170)
![KakaoTalk_20240111_145530946](https://github.com/TeamHY/Astrobirth/assets/28684443/2a4744b6-50a9-4296-bb63-bacaefbc0e1b)

**Comment by pdom0327** [comment]
<img width="1196" alt="image" src="https://github.com/TeamHY/Astrobirth/assets/12953393/b7a074c3-acc6-470f-8e7a-6c1b17eec7f6">
챌린지 이름으로 루아에서 판단하기 때문에 challenges.lua 파일도 같이 수정해주셔야 합니다.
