### ISSUE TITLE
신규 아이템 : 캄 마인드

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#106]
![collectibles_auri_calmmind](https://github.com/TeamHY/Astrobirth/assets/28684443/ec49257e-e6b9-4d5e-ab4c-348e22fa956e)
[auri_2283703372.zip](https://github.com/TeamHY/Astrobirth/files/13931481/auri_2283703372.zip)

-1초당 공격력 0.01 증가
-패널티 피격 시 60초간 공격력 증가 효과 중단
-원본은 아우리 모드 아이템이고, 코드 참고용으로 전체 모드 파일 업로드 해놨음
-레아의 기본 컨셉으로 설정할거라 우선 순위 매우 높음

**Comment by pdom0327** [comment]
단순한 효과라서 모드 아이템 그대로 옮길 필요 없을거 같아 임시로 이미지, 이름 변경했습니다
