### ISSUE TITLE
밸런스: 비스트 방

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#109]
도그마 룸과 마찬가지로 오라를 가진 빠가지 4개 소환

**Comment by pdom0327** [comment]
<img width="844" alt="image" src="https://github.com/TeamHY/Astrobirth/assets/12953393/1bfe35a5-d62b-4d45-945b-732123da2593">

**Comment by iwt2hw** [comment]
-비스트 방에서 피격(패널티) 시 현재 체력과 부활 유무를 따지지 않고, 즉사하도록 변경
└현재 대결모드에 짜여져 있는 다모클래스 즉사 패널티 50% 버전이 100% 버전이라고 생각하면됨
