### ISSUE TITLE
크레인을 적극적으로 활용하고 싶은데, 아래 방법이 구현 가능 합니까?

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#111]
현재 대결 메타의 경우, 크레인(도박)에 5원 사용할빠엔 킾하거나 그 돈으로 상점 지르는게 효율적이라 크레인이 활용되고 있지 않습니다
크레인에 배열을 건드는 방법도 있지만 이 경우 운빨졷망겜이 되어버려서 섣불리 못 건드리고 있습니다

Q : 특정 조건 때 크레인은 시도하되, 동전은 소모되지 않도록 가능합니까?

**Comment by pdom0327** [comment]
크레인에서 접촉 시 돈이 소모되면 다시 복구하는 방식으로 구현 가능할 것 같습니다.

**Comment by iwt2hw** [comment]
확인
