### ISSUE TITLE
예전에 카그에서 사용하던 캐릭터들 대결 모드에 이식

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#113]
[playable final bosses_845875038.zip](https://github.com/TeamHY/Astrobirth/files/14001230/playable.final.bosses_845875038.zip)

-챌린지 같은 시스템 없어도 됨 (설명 및 시작 아이템 전부 직접 설정할거라서 필요없음. 이미지 깡통만 있으면 됨

**Comment by pdom0327** [comment]
<img width="678" alt="image" src="https://github.com/TeamHY/Astrobirth/assets/12953393/0004ce94-2873-4445-8946-987da9bac84a">

**Comment by pdom0327** [comment]
임시 캐릭터 추가했습니다. 원하시는 캐릭터 있으시면 이미지 만들어올게요
