### ISSUE TITLE
신규 아이템: 이지 모드(EZ Mode)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#115]
-소지 상태일 경우 스테이지 입장 시 마다 홀리 카드 소환
-1스테이지 11시 방향에 무조건 소환

뉴비 진입을 위한 아이템
![959](https://github.com/TeamHY/Astrobirth/assets/28684443/0efc46a7-cb1b-4f03-8a85-af35d78dc5d4)

**Comment by pdom0327** [comment]
noeden quest 태그 추가해뒀습니다.
