### ISSUE TITLE
신규 장신구: 노스텔지아(Nostalgia)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#116]
1. 장신 구 즉시 획득됩니다
2. 장신구를 소지한 채로 보스방 클리어 시, 노농(오리지널 아이작) 관련된 아이템이 2개 드랍되며, 해당 장신구는 사라집니다
3. 황금 효과는 존재하지 않습니다

![Nostalgia](https://github.com/TeamHY/Astrobirth/assets/28684443/5610a022-3bbf-4421-8b6d-192f0177d105)

**Comment by pdom0327** [comment]
노농 출신 아이템들이 등장하게 하면 될까요?

**Comment by iwt2hw** [comment]
2-2 ) 아이템 2개 모두 획득할 수 있는게 아니라, 이지선다 형식으로임 까먹었음 ㅈㅅㅈㅅ
