### ISSUE TITLE
캐릭터 업데이트: 레아

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#117]
-생득권 획득 시, 레아의 기본 아이템인 증폭하는 심장을 하나 더 획득 하고 있는 효과 적용
└간단하게 증폭하는 심장 2개먹었다고 생각하면 됨

예) 생득권1개, 증폭하는 심장1개 = 2개 판정
예) 생득권2개, 증폭하는 심장1개 = 3개 중첩 판정
예) 생득권2개, 증폭하는 심장2개 = 4개 중첩 판정

**Comment by pdom0327** [comment]
시작, 밴 아이템 리스트 추가했습니다.
