### ISSUE TITLE
거울 장신구 미적용 관련

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#118]
1. 조건은 모르나 간헐적으로 거울 장신구를 소지한 상태에서 패시브 아이템 획득 시 복사가 되지 않음
2. 나도 처음엔 아이템을 획득하면서 카드 사용같은 모션이 원인인줄 알았는데, 오늘 생방송중에도 두번 발생함
3. 원인 찾기가 어렵다면 캐릭터에게 지급이 아닌 소환으로 변경해도됨

**Comment by pdom0327** [comment]
버그 발생 시간대가 언제인지 알 수 있을까요...?
