### ISSUE TITLE
패시브 아이템 업데이트: 학사학위(Bachelor's Degree)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#122]
**-학사학위에 알약 효과를 투시하는 효과가 추가됩니다**

해당 아이템 획득 시, 처녀자리, 럭풋, PHD 등의 알약 긍정, 부정 효과가 씹히는 "버그" 가 존재함

단 해당 현상은 버그긴 하지만 심각한 사안으로 취급 하지 않기로 함

버그 픽스보단 학사 학위를 버프하기로 결정

**Comment by pdom0327** [comment]
버그는 아닙니다. 모드 아이템이 더 나중에 적용되는 문제라서 긍정, 부정 아이템 있을 때 나올 알약을 따로 추가하는 식으로 구현 할 수 있어요.
