### ISSUE TITLE
아이템 업데이트: 이지모드

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#127]
기존 홀리 카드 드랍하는 효과에 아래 효과 추가

-패널티 피격을 당하더라도 에이플이 등장되지 않거나, 사라지지 않음

와카바 모드에서 일부 캐릭터나 아이템들이 패널티 피격 면역 시스템 있더라

[pudding and wakaba_2543118811.zip](https://github.com/TeamHY/Astrobirth/files/14274985/pudding.and.wakaba_2543118811.zip)

참고용 모드

**Comment by pdom0327** [comment]
패널티 피격 면역이면 악마방 확률도 안 깍일텐데 괜찮을까요?

**Comment by iwt2hw** [comment]
1. 의도된 사항은 에이플만 지켜지는거긴함
2. 에이플 피격 + 악마방 확률 피격 분리가 어려울 경우, 피격 시 악마방 확률이랑 에이플 둘 다 패널티 안들어가는 코드로 짜여져도 상관은 없음

**Comment by pdom0327** [comment]
2번으로 구현했습니다. 1번은 에이플을 새로 만들어야합니다.

**Comment by pdom0327** [comment]
업로드 안 되어있었네요. 방금 업로드 했습니다.
