### ISSUE TITLE
커스텀 아이템에 플레이버 텍스트 추가할 수 있도록 패치

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#131]
아이템 획득 시 아래 등장하는 부설명을 한글로도 내가 직접 넣을 수 있게 했으면 좋겠음

와카바 모드의 경우 한글로 해놓고 먹어도 뜨던데 와카바님한테 물어봐도될듯?

**Comment by pdom0327** [comment]
![image](https://github.com/TeamHY/Astrobirth/assets/12953393/e99ee16a-f984-4f5c-b1d0-04b7f3591999)
![image](https://github.com/TeamHY/Astrobirth/assets/12953393/79dbdc15-34fd-4466-a420-611279b72e75)

테스트 해보니 한글로 넣어도 작동합니다. 영문도 함께 작성하길 원하시는건가요?

+ 아이템 이름도 한글로 적용되지만 루아 쪽도 함께 수정이 필요합니다.

**Comment by kohashiwakaba** [comment]
xml 상에서의 한글 설정은 절대 추천하지 않습니다. 한국어 이외의 언어 설정 시 정상적으로 작동하지 않을 확률이 매우 높으며 (_더군다나 대결모드는 REPENTOGON을 사용하지 않기 때문에 튕길 위험이 높음_) 무엇보다도 대결 유저의 언어 설정도 강제로 한국어로 적용해야 되는 문제가 있기 때문입니다.

따라서 아예 모든 문구 정보(이름, 부설명)를 lua 상에서 저장 및 처리하는 것을 추천합니다.

와카바모드의 경우 모든 언어별 문구 정보(EID 설명 정보 포함)를 한 군데에 모아 관리하고 있는데 대충 아래처럼 이루어지고 있습니다.
```
-- 와카바 모드의 경우 아래 테이블이 언어별로 설정되어 있으나 
-- 여기선 굳이 필요 없으므로 단일 언어로 관리함. 
-- 단, 종류별(아이템/장신구/카드/알약)로 따로 관리해야 됨.
local descriptionData_kr = {
  [Astro.Collectible.ABCD] = {
    name = "에덴 아이템",
    description = "EID 설명 정보",
    queueDesc = "안녕하세요!",
  },
  [Astro.Collectible.ISAAC] = {
    name = "아이작 아이템",
    description = "EID 설명 정보",
    queueDesc = "안녕하세요!",
  },
}
```

구현 방식은 REPENTOGON 적용 여부에 따라 확연히 차이나는데 대결모드는 REPENTOGON을 사용하지 않는 것을 전제로 되어 있으니 REPENTOGON을 사용한 방법은 따로 적지 않습니다. 아래 코드는 ezItems( https://github.com/ddeeddii/ezitems-web/blob/main/src/modules/template.js )의 코드를 기반으로 아이템을 드는 모션이 시작되는 순간 플레이버 텍스트를 표기하도록 합니다.
```
if Options.Language == "kr" then -- 인게임 언어가 한국어가 아닌 경우 불필요
local i_queueLastFrame = {}
local i_queueNow = {}

wakaba:AddCallback(ModCallbacks.MC_POST_PLAYER_UPDATE, function (_, player) 
  local descTable = descriptionData_kr
  local initSeed = tostring(player.InitSeed)

  i_queueNow[initSeed] = player.QueuedItem.Item
  if (i_queueNow[initSeed] ~= nil) then
    if i_queueNow[initSeed].ID and descTable[i_queueNow[initSeed].ID] and i_queueNow[initSeed]:IsCollectible() and i_queueLastFrame[initSeed] == nil then
      -- 이전 큐가 비어 있음 + 현재 큐가 커스텀 아이템일 경우에만 표시
      local entry = descTable[i_queueNow[initSeed].ID]
      local itemName = entry.name
      local queueDesc = entry.queueDesc
      Game():GetHUD():ShowItemText(itemName, queueDesc) --이 시점이 플레이버 텍스트가 나오는 시점
    end
  end
  i_queueLastFrame[initSeed] = i_queueNow[initSeed]
end)
end
```

장신구의 경우 편의 상 생략하였으며 (아이템 체크랑 거의 같음) 카드, 알약의 경우 REPENTOGON이 필수이므로 따로 다루지 않겠습니다.

**Comment by iwt2hw** [comment]
1. 영문 플레이버 텍스트는 필요 없음
2. 한글로 설정 시 아이템 이름과 플레이버 텍스트를 한글로 출력하고 싶음

**Comment by iwt2hw** [comment]
즉 와카바님이 짜주신 위 코드처럼 인게임 언어 설정이 "한글" 일경우 아이템 이름이랑 플레이버 텍스트를 한글로 쓰고 싶음

**Comment by pdom0327** [comment]
![image](https://github.com/TeamHY/Astrobirth/assets/12953393/63ba0093-6752-49f4-a10d-e280dc8324ce)
각 아이템의 "..." 부분을 수정해주시면 됩니다.
