### ISSUE TITLE
#2캐릭터 업데이트: 아자젤

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#132]
**-캐릭터가 아자젤이며, 에이플을 소지한 상태에서 보스방(스테이지 상관X) 클리어 판정이 됐을 경우, 아이 오브 오컬트
![5 100 572 - Occult Eye](https://github.com/TeamHY/Astrobirth/assets/28684443/bdfafa90-f926-4fba-8807-38c63cd91b8a)
가 "소환" 됩니다
-중복 적용이 가능한 아이템이라 배열에서는 지워지지 않도록 합니다
-이미 오컬트를 가지고 있다면 소환되지 않으며, 4각등 다른 효과로 인하여 오컬트를 소지하고 있지 않은 상태에서 상기 조건을 만족하고 보스방을 클리어 했을 경우 다시 소환될 수 있습니다

-캐릭터가 아자젤이며, 에이플과 를 소지한 상태에서 보스방(스테이지 상관X) 클리어 한정이 됐을 경우, 
![5 100 118 - Brimstone](https://github.com/TeamHY/Astrobirth/assets/28684443/2d3a2821-9ebf-41f7-a789-63cc09fa165b)
가 "소환 됩니다
-마찬가지로 중복 적용이 가능한 아이템이라 배열에서는 지워지지 않도록 합니다**
-이미 혈사포를 가지고 있다면 소환되지 않으며, 4각등 다른 효과로 인하여 혈사포를 소지하고 있지 않은 상태에서 상기 조건을 만족하고 보스방을 클리어 했을 경우 다시 소환될 수 있습니다

닥터가 에이플 가지고 있으면 로켓이랑 폭발 면역 되는거처럼 아자젤 성장형된다고 이해하는 컨셉임

**Comment by pdom0327** [comment]
한 번 소환된 뒤에는 중복 소환되지는 않는거죠?

**Comment by iwt2hw** [comment]
어떠한 이유로 아이템이 지워진다면 다시 소환, 아이템을 소지하고 있다면 소환 X

**Comment by iwt2hw** [comment]
너무 복잡해질거같아서 글 다시 수정했음
