### ISSUE TITLE
신규 장신구 업데이트: 교리, 구피의 눈, 천체 왕관, 

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#139]
![Doctrine](https://github.com/TeamHY/Astrobirth/assets/28684443/e649beeb-fc4e-4f6e-aac4-abba6f1a408c)
![Planetarium Crown](https://github.com/TeamHY/Astrobirth/assets/28684443/6f53e473-4700-40fa-9381-c7490390fcf9)
![trinkets_guppyseye](https://github.com/TeamHY/Astrobirth/assets/28684443/269c1f12-0c69-49d8-aacf-62a090cd1c16)

**교리(Doctrine)**
1. 스테이지 진입 시 축복 1회 효과가 적용됩니다 (희생방 피격 시 3,5번째 적용되는 축복 효과와 동일)
2. 해당 장신구를 소지한 상태에서는 저주가 적용되지 않습니다 (에이플 소지 시 저주가 걸리지 않는 코드와 동일)
3. 황금 or 맘박스 적용 시 +1 판정으로 효과가 강화됩니다 (둘 다 가지고 있는 상태라도 중복 적용되지 않습니다)

**구피의 눈(Guppy's Eyes)**
1. 캐릭터가 존재하는 방 기준 2칸이내에 일반방들의 위치를 보여줍니다 (탄광모자와 동일하나 특수방들의 위치는 보여주지 않음)
2. 소지 시 행운이 -3 감소됩니다
3. 황금 및 맘박스 상태일 경우 구피 세트를 +1 카운트 해줍니다 (둘 다 가지고 있는 상태라도 중복 적용되지 않습니다)

**천체 왕관(Planetarium Crown)**
1. 황금방 입장 시 행성방 아이템 1개가 소환되며, 해당 장신구는 제거됩니다
2. 황금 및 맘박스 적용 상태일 경우 등장하는 아이템이 2개로 됩니다 (둘 다 가지고 있는 상태라도 중복 적용되지 않습니다)
비고 : 황금방 구조 변수 방지를 위해, 황금방 내에 좌표가 아닌 캐릭터 기준 좌표로 아이템을 소환할 것

_깃허브에 이미지와 XML 업데이트 작업까지 완료 해놨어~~_

**Comment by pdom0327** [comment]
장신구 구피셋은 추가할 방법을 모르겠습니다.

**Comment by iwt2hw** [comment]
1. 구피의 눈깔은 아이템 명칭을 모시의 눈으로 변경해서 1,2번 효과만 구현

**Comment by iwt2hw** [comment]
구피눈 장신구 모드에 아래 모드 효과를 삽입

https://steamcommunity.com/sharedfiles/filedetails/?id=3014658067&searchtext=guppys
