### ISSUE TITLE
에픽빔 모드 분할

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#140]
저번에 카톡으로 이야기 했던 에픽빔 모드 분할 작업입니다

1. 3퀄리티 등장 시 특정 음원 파일 출력 (파일은 어차피 내가 직접 교체할거고, 확장자도 어떤걸로 해도 상관 無)
2. 4퀄리티 등장 시 현재 대결 모드 에픽빔 파일 출력
3. 3퀄리티,4 퀄리티를 제외한 기타 기능들 (지속 시간, 속도, 볼륨 크기, 방 마다 한번 등) 전부 대결 모드와 동일하게 설정

※에덴런 랜덤보스 같은 솔플에서 사용하기 위함
※완성이 된다면 내가 직접 스팀에 업로드 할거라 여기나 카톡으로 파일 자체 부탁!

**Comment by pdom0327** [comment]
[epic beam.zip](https://github.com/TeamHY/Astrobirth/files/14420576/epic.beam.zip)

resources/sfx/feedback/epic1 - 3 퀄리티
resources/sfx/feedback/epic2 - 4 퀄리티

**Comment by pdom0327** [comment]
대결 모드도 함께 업뎃해야합니다.
