### ISSUE TITLE
퀵옵션 모드 필터 관련 기능

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#141]
[Q_Option.zip](https://github.com/TeamHY/Astrobirth/files/14414960/Q_Option.zip)

-현재 방이 클리어 상태일 경우 인게임 필터 **꺼짐** 상태로 적용 (아래 사진 상태)
![KakaoTalk_20240227_151453054](https://github.com/TeamHY/Astrobirth/assets/28684443/991240dd-2cd3-44b2-b202-bed2e07954be)

-현재 방이 클리어 상태가 **아닐** 경우 **켜짐** 상태로 적용 (아래 사진 상태)
![KakaoTalk_20240227_151455658](https://github.com/TeamHY/Astrobirth/assets/28684443/ab102f4c-364f-4a27-a5a6-d2c59caf8fa7)

**Comment by pdom0327** [comment]
[Q_Option.zip](https://github.com/TeamHY/Astrobirth/files/14419608/Q_Option.zip)
