### ISSUE TITLE
편의성 패치 : 블러디 러스트, 블러디 거스트 관련

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#146]
![KakaoTalk_20240304_172818329](https://github.com/TeamHY/Astrobirth/assets/28684443/5feac4ab-4b80-45d7-b231-7925ab4da90f)

**가능합니까?**

**Comment by pdom0327** [comment]
효과음만 제거했습니다.

**Comment by iwt2hw** [comment]
와우 센스 굳굳 오히려 좋아
