### ISSUE TITLE
신규 아이템 : 앱솔루트 구피(Absolut Guppy)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#147]
![Absolut Guppy](https://github.com/TeamHY/Astrobirth/assets/28684443/bff8f074-054e-475d-a36b-23d80bb33307)

**1. 해당 아이템 소지 시 구피 세트 카운트+1 효과가 적용됩니다
2. 구피 카운트 효과는 중복 적용이 가능하며, 횟수만큼 카운트 됩니다
3. 해당 아이템을 소지한 상태에서 구피 세트일 경우, 파리 소환 확률이 100% 가 됩니다 (너프전 구피)**

3번 구현이 어려울 경우 아이작 장신구중 생선꼬리(fish tail) 캐릭터에게 할당시키거나 즉시 흡수시키는 방법으로 구현해도 됩니다
![KakaoTalk_20240304_173332367](https://github.com/TeamHY/Astrobirth/assets/28684443/2992d2fe-25f2-4de6-ad91-c538051e6b2f)

해당 모드는 언너프 구피 모드
참고될거같아서 링크 일단 넣어놓을게

https://steamcommunity.com/sharedfiles/filedetails/?id=2499788312&searchtext=guppys

**Comment by pdom0327** [comment]
fish tail과 동등한 효과를 추가하는게 쉬울거같은데 그렇게 진행해도 될까요?

**Comment by iwt2hw** [comment]
ㅇㅇㅇㅇ 상관 없음

단 EID 설명에 어떤 방식을 사용하는지 기재

EX : 생선꼬리 장신구 효과를 얻습니다
EX : 생선꼬리 장신구가 캐릭터에게 즉시 흡수됩니다
