### ISSUE TITLE
신규 캐릭터 디아벨스타 실험체 1번에 적용

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#151]
[Diabellstar.zip](https://github.com/TeamHY/Astrobirth/files/14522069/Diabellstar.zip)

추가) 디아벨스타 기본 아이템이 원죄보(유령 소환) 아이템 추가

**Comment by pdom0327** [comment]
효과를 캐릭터 내장으로 만들었는데 아이템 추가로 바꿀까요?

**Comment by iwt2hw** [comment]
ㅇㅇㅇ내장으로 할 필요는 없어 어차피 여러개 먹어도 중복 가능하게 할거니까
