### ISSUE TITLE
로튼베이비 자폭파리 제한이 해제됨

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#153]
![KakaoTalk_20240309_054053125](https://github.com/TeamHY/Astrobirth/assets/28684443/eb58c3a1-7412-4574-8ca6-99df3cc0e1f3)

원인은 아마 이번에 패치한 구피 관련이 아닐까 싶음

**Comment by pdom0327** [comment]
위 상황은 앱솔 구피 구현을 변경해서 해결할 수 있을 거 같습니다.

![image](https://github.com/TeamHY/Astrobirth/assets/12953393/bf597577-a6c6-4165-a961-aecf96f1467c)
그런데 위와 별개로 섬망 구피를 획득하면 또 비슷한 문제가 생깁니다. 이건 파리 자체를 수정해야 할듯 한데 원하시는 효과가 이 파리로 변경이 맞나요? 딱히 특수 효과가 없는거 같아서요.

**Comment by iwt2hw** [comment]
해당 파리는 그냥 섬망 이미지 색맞춤이라서 상관 없음. 효과 없는거 인지하고 부탁한거임 ㅇㅇ
