### ISSUE TITLE
에픽빔 모드 관련 및 롤백

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#154]
맨 아래 요약만 읽어도 됨

에픽빔 분리 패치이후 시범해봤지만 다시 원래대로 되돌리는게 좋을 거 같습니다
초기 에픽빔 모드의 목적은 아이작을 잘 모르더라도 빔이 나오는 순간 "아 저거 좋은템이구나" 용도였습니다

분리패치이후 대결러들은 굳이 에픽빔 모드를 다운받지않고, 상대방이 좋은 아이템 등장 시 빔으로 알 수 있던 환경이 사라졌습니다

대결의 경우 상대방이 어떤 템을 먹었는지 모니터링하면서 맞춰가는게 중요한데 해당 현상이 힘들어졌습니다

예시로 상대방이 락바텀을 먹었다면 그에 맞춰 빠르게 진행을 해야하는데 상대방 화면에 빔이 출력되지 않으니 알 수가 없으며, 시청자들또한 상대방이 뭘 먹었는지 관전 포인트가 줄어서 분리 패치는 롤백해야 될거 같습니다

또한 싱글 플레이의 경우 퀄리티3 아이템이 과도하게 등장 해, 정신이 많이 사납습니다

간단 요약
1. 솔플은 독자적인 에픽빔 모드, 대결은 에픽빔 시스템 자체를 대결에 내장을 원함 (롤백)
2. 솔플&대결 상관없이 블라인드 및 히든 스테이지 확인 불가능한 아이템은 에픽빔이 출력되지 않도록 적용
3. 솔플 에픽빔 모드의 경우 기존 시스템을 유지하되 예외처리할 수 있는 기능이 필요함
└성능에 비해 퀄리티가 맞지 않은 아이템 등장 시 과도한 빔 출력이 정신 사나움. 예외 처리 기능을 사용하면 모드 아이템(3,4퀄리티) 등장 시 에도 별도 작업을 하지 않더라도 빔이 출력 가능함

**Comment by pdom0327** [comment]
대결 모드 쪽 적용했는데 히든 스테이지 블라인드 체크 로직에서 성능 문제가 생길 수도 있습니다.

**Comment by iwt2hw** [comment]
성능 문제라면 블라인드가 풀리면서 잠깐 걸리는 렉을 말하는거? 이거면 큰 상관없고 모드 자체가 렉이 걸릴 수 있는건 아니지 ?

**Comment by pdom0327** [comment]
항시는 아니구요 히든루트 황금방 입장 시 약간 렉 생길 수 있어요

**Comment by pdom0327** [comment]
[epic beam.zip](https://github.com/TeamHY/Astrobirth/files/14586460/epic.beam.zip)
물 스테이지 황금방에서는 아예 작동하지 않는 문제가 있습니다. 다른 스테이지에서는 제대로 작동합니다.
