### ISSUE TITLE
패시브 아이템 : 타락한 오브(Fallen Orb) 리뉴얼

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#161]
기존효과에서 완전히 초기화 후 리뉴얼

**-해당 아이템이 소지중일 경우 0,1퀄리티 아이템이 등장되지 않습니다**

**Comment by pdom0327** [comment]
기존 코드에서 수정해 획득 시 0, 1 퀄리티 배열 제거로 구현되어 있습니다.
소지 아이템에서 타락한 오브가 지워지면 배열을 다시 복구하도록 변경해야 하나요?

**Comment by iwt2hw** [comment]
1. 배열 다시 복구되는걸로 하는게 1순위
2. 1번이 어렵다면 2번도 상관 없음 안귀찮은걸로 해도 됨

 뭘로 했는지만 깃허브에 적어만 놔주셈

**Comment by pdom0327** [comment]
복구하지 않는 걸로 업로드 되어 있습니다.
