### ISSUE TITLE
astro/things.lua 파일 분리

### ISSUE THREAD

**Issue by chan-hui** [TeamHY/Astrobirth#162]
헌영님 요청사항에 관한 코드들만 따로 넣어 추가한 things.lua 파일이 기능별 분리되지 않고 남아있습니다.

각 기능 별 해당하는 lua 파일 존재 시 해당 파일로 이동 및 존재하지 않더라도 파일 추가 및 분리해주시면 감사드리겠습니다.

제가 해도 되는 부분이지만 제가 현재 프로젝트의 전반적인 이해도가 적고 도저히 부대에서 폰으로 하는 건 안되겠어서...

**Comment by iwt2hw** [comment]
프돔이말고 딴놈이라 놀랐네

**Comment by iwt2hw** [comment]
근데 굳이 냅둬도 크게 상관없어서 지금 다른것들도 할거 개많아서 우선 사항이 아님

**Comment by pdom0327** [comment]
1558e12619ce8c5bfcfe8ee88bf53dbd6dbddbe0 정리했습니다
