### ISSUE TITLE
에픽빔이 관련 추가 업데이트

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#167]
**사망증명서 방에서는 에픽빔이 발동되지 않도록 변경 (대결 모드 + 분할되어있는 에픽빔 모드 둘 다 적용)**

[epic beam.zip](https://github.com/TeamHY/Astrobirth/files/14752384/epic.beam.zip)

**Comment by pdom0327** [comment]
https://github.com/TeamHY/ExtraMods
별도 모드들을 위한 레포를 새로 생성했습니다.
이슈는 Astrobirth에서 관리하지만 모드 파일은 [TeamHY/ExtraMods](https://github.com/TeamHY/ExtraMods)에서 동기화하시면 됩니다.

**Comment by iwt2hw** [comment]
확인. 다음부터는 파일만 저기에 올리면 되는거지? 이슈는 여기에 기재하고 ㅇㅇ;

**Comment by pdom0327** [comment]
넵 맞습니다!

**Comment by pdom0327** [comment]
별도 모드 업데이트 했습니다
