### ISSUE TITLE
캐릭터 선택 시 확률적으로 알트로 변경되는 시스템 추가

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#169]
현재 대결에서 1R의 경우 다양성을 위해 노말 랜덤으로 진행하고 있으며, 1R 알트캐 확장을 위해 아래 기능이 필요함

**-해당 기능은 "랜덤" 시에만 작동되어야 함
-노말 캐릭터(A side) 에서 랜덤으로 캐릭터가 나왔을 경우 확률적(50%)으로 알트로 변경
-각 캐릭터마다 적용되는 유무를 직접 설정할 수 있어야 함 
└현재 대결모드는 로스트, 알트 로스트가 전부 밸런싱이 끝난 상태라 어떤게 나와도 상관없지만, 라자루스의 경우에는 아직 알트 라자루스가 미완성 밸런스 상태입니다. 이 부분은 루아로 true false 조정할 수 있으면 좋겠습니다**

노말 캐릭터(A side) 에서 랜덤으로 캐릭터가 나왔을 경우 확률적(50%)으로 알트로 변경

**Comment by pdom0327** [comment]
랜덤으로 돌린 캐릭터인지 확인할 방법이 없습니다.
