### ISSUE TITLE
다크 범 관련

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#170]
다크 범 획득 시 비밀방과, 일급 비밀방에 적용되는 거미가 제거되는 코드를,

다크 범 소지에서도 적용되도록 변경

**Comment by pdom0327** [comment]
지금 코드 대로면 다크 범 소지 시 모든 빨간 거미가 등장하지 않는데 그래도 괜찮을까요?

**Comment by iwt2hw** [comment]
아예 등장하지 않는것이 의도된게 맞습니다
