### ISSUE TITLE
8스테이지 보스방 강화 심장

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#172]
![KakaoTalk_20240402_133156401](https://github.com/TeamHY/Astrobirth/assets/28684443/c6281125-90f6-4f60-b689-2d74148908a9)

8스테이지 it lives 심장을 마더 루트 강화 심장으로 등장하고 싶습니다

리노베이터는 해당 몬스터 이미지가 등록이 안되어있는데, 루아로 소환 가능합니까 ?

좌표는 해당 이미지 가운데입니다
https://drive.google.com/file/d/1VoSFfcyOS5yEBXm9At4WNVg2P-OW7mS_/view?usp=sharing 리노베이터 (용량 문제로 구글 드라이브)

**Comment by iwt2hw** [comment]
좌표가 힘들면 리노베이터에서 업데이트도 괜찮습니다
리노베이터 파일 첨부 해놨습니다

**Comment by pdom0327** [comment]
https://drive.google.com/file/d/1fo4LDmKNeuzgKTGoS79oxLm43ml1hUvo/view?usp=sharing
리노베이터 업데이트 했습니다.
