### ISSUE TITLE
EID 모드의 경우 첫 엄마발을 잡지 않았을 경우, 업적이 해금되지않는다는 문구가 출력됩니다

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#178]
**EID 모드의 경우 첫 엄마발을 잡지 않았을 경우, 업적이 해금되지않는다는 문구가 출력됩니다

대결 모드의 경우 데드갓 상태에서 플레이를 기준으로 제작되어있는데 EID 모드처럼 현재 진행중인 세이브 상태가 데드갓이 아닐경우 경고 문구를 출력시킬 수 있을까요?**

**Comment by pdom0327** [comment]
EID의 경우는 묵시록, 미트볼의 언락 여부를 통해 체크합니다. 데드갓은 언락 아이템이 없어서 불가능합니다.

(Repentogon 필요) https://repentogon.com/enums/Achievement.html?h=achievement

**Comment by iwt2hw** [comment]
해당 사항 그대로 기준을 데드갓으로해서 작업

**Comment by pdom0327** [comment]
<img width="841" alt="image" src="https://github.com/TeamHY/Astrobirth/assets/12953393/8688adf1-44c0-4973-991c-c8284851f6f8">
