### ISSUE TITLE
타락한 오브의 경우

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#180]
1. 타락한 오브 획득
2. 타락한 오브 4각등 이벤트가 발생되어 해당 아이템 제거

위 같은 상황이 발생되어도 이미 타락한 오브로 지워진 배열은 돌아오지 않는걸로 알고 있습니다
로스트의 생득권또한 위와 완전히 같은지요 ?

**Q : 로스트 생득권도 지워지면 배열 복구 안되는지가 궁금하며, 이거또한 타락한 오브 처럼 복구가 되지 않는게 의도임**

**Comment by pdom0327** [comment]
배열 복구 안 되는 것이 맞습니다.
