### ISSUE TITLE
퀵옵션 기능 관련 2종 추가

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#181]
[Q_Option.zip](https://github.com/TeamHY/Astrobirth/files/15062999/Q_Option.zip)

-신규 기능
1. 클리어 되지 않은 "모든"방 입장 시 미니맵에 투명도를 0으로 설정합니다
2. 방 클리어 판정이 적용되었을 경우 미니맵 투명도를 4로 설정합니다

-기존 효과
기존 : 보스방 입장 시, 아이템 허드 off -> 보스방 클리어 시 아이템 허드 small 설정
변경 : 클리어 되지 않은 "모든 방" 입장 시 아이템 허드 off -> 방 클리어 판정이 적용되었을 경우 스몰로 초기화

**Comment by pdom0327** [comment]
> -신규 기능
> 
> 1. 클리어 되지 않은 "모든"방 입장 시 미니맵에 투명도를 0으로 설정합니다
> 2. 방 클리어 판정이 적용되었을 경우 미니맵 투명도를 4로 설정합니다

왜인지는 모르겠는데 투명도 0으로 변경은 되고 투명도 0.4로 변경은 안 먹힙니다.

**Comment by iwt2hw** [comment]
그럼 일단 기존 효과(아이템 허드 관련) 만 업데이트 부탁 드립니다

**Comment by pdom0327** [comment]
[Q_Option.zip](https://github.com/TeamHY/Astrobirth/files/15208181/Q_Option.zip)
