### ISSUE TITLE
신규 캐릭터 : 원죄의 디아벨제(Diabellze the Original Sinkeeper)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#183]
![KakaoTalk_20240421_224114995](https://github.com/TeamHY/Astrobirth/assets/28684443/56a13ec5-8a37-4a69-81b7-6cae0afff6ea)
![KakaoTalk_20240421_224112617](https://github.com/TeamHY/Astrobirth/assets/28684443/c58b2cc0-c293-436a-a948-b578d26d236b)

해당 캐릭터는 디아벨스타의 알트 포지션으로 추가

**Comment by pdom0327** [comment]
<img width="148" alt="image" src="https://github.com/TeamHY/Astrobirth/assets/12953393/d25e9dda-1921-4f4b-9411-6158a9386239">

![image](https://github.com/TeamHY/Astrobirth/assets/12953393/e380d9e6-fca2-42f4-a2fb-fa4715816445)

긴 머리에 몸통이 가려져서 수정이 필요합니다.
