### ISSUE TITLE
Feat: 신규 시스템 : 아이템 블록제(리미트 레귤레이션)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#200]
대결에서 오버 파워를 가진 아이템들은 비중이 설정되어 있습니다
그렇지만 로그라이크(운빨) 겜 특성상 비중이 낮더라도 연속으로 등장하는 하는 상황이 발생합니다
예) 1R 제왕절개, 사증 사용하고 다음판 또 등장

이런 상황을 막기 위해 전판에 사용한 아이템은, 다음판에 배열 지워지는 시스템이 있으면 좋겠습니다
만약 리셋을 할 경우 1코인과 축복을 코스트로 사용하기 때문에, 이지선다를 요구하고 이는 대결모드와 방송적인 면에서도 좋습니다

✅한줄 요약
-등록한 아이템을 획득하였을경우 다음판 모든 배열에서 제거 (현재 짜여져 있는 밴 시스템과 동일하게 하면 될듯
-액티브는 체크하지 않아도 됨 (코드상 가능해도 ㄴㄴ)
-추가) 다음판에 지워지는 아이템들이 등장 후, 바로 제거되는 애니메이션 추가

**Comment by pdom0327** [comment]
액티브 적용 안 하는게 오히려 추가 체크 필요해서 일단 액티브도 적용됩니다.
