### ISSUE TITLE
ban.lua 관련

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#202]
**커스텀 캐릭터들이 존재하지 않습니다 ㅠ^ㅠ**
**수견사 카배터리 금지 및 기타 다른 아이템 밴이 시급합니다**

**-밴 시스템의 커스텀 캐릭터들 추가**

**Comment by pdom0327** [comment]
![IMG_6441](https://github.com/TeamHY/Astrobirth/assets/12953393/7e0c9152-6a5e-440c-a566-26d6d857f442)
추가 되어있습니다

**Comment by iwt2hw** [comment]
뒤지도록 하겠습니다. ㅈㅅㅈㅅ
