### ISSUE TITLE
EID: 낙제

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#203]
낙제 황금효과가 설명이 누락되어 있습니다

**Comment by pdom0327** [comment]
eid 황금 장신구 표기는 기존 바닐라 장신구에 새로운 황금 효과를 추가한 것만 상시 표기하고 있습니다.
커스텀 장신구`(ex. bloody bandage: 맵에 저주방의 위치가 표시됩니다.)`는 황금 or 맘박스 보유 중일 때만 표기되는데 전부 상시 표기로 변경할까요?

**Comment by iwt2hw** [comment]
네 전부 상시 표기 해주세요 (애초에 이게 의도였음)
