### ISSUE TITLE
feat: Blood Of Hatred(증오의 피)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#207]
-해당 아이템 2악마 세트로 취급되도록 변경

**Comment by pdom0327** [comment]
악마셋 2개 먹은 효과라는 뜻인가요?

**Comment by iwt2hw** [comment]
네 맞습니다

**Comment by pdom0327** [comment]
획득 시 두 개 들어오는 방식으로 구현해야할 것 같습니다. 현재 중첩 효과는 없는 상태인데 이렇게 작업할까요?

**Comment by iwt2hw** [comment]
넵. 획든 시 2개 들어오도록 합니다
1.중첩은 그냥 알아서 (eid에만 어떤식인지 기재. 밸런스쪽은 어케하든 상관x)
2. Eid 해당 아이템이 2개 들어온다는 문구 추가
