### ISSUE TITLE
Feat: 신규 시스템 : 아이템 블록제(리미트 레귤레이션)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#212]
아이템 애니메이션이 너무 순식간에 지나가서 방송에서 보여주기가 힘들어 보입니다

아래 방법 가능할까요?

1안) 시작방일경우 밴 아이템 목록을 순차적으로 계속 반복하면서 로테이션 하면서 보여주기
2안) 밴 아이템을 확인 가능하도록 속도 조절

**Comment by pdom0327** [comment]
둘다 가능합니다
