### ISSUE TITLE
bug: f5 관련 기능

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#219]
![KakaoTalk_20240526_212150814](https://github.com/TeamHY/Astrobirth/assets/28684443/ea132105-1735-446e-a21e-1c0165916ce4)

아마 데이비드랑 루시 추가하면서 발생된듯

**Comment by pdom0327** [comment]
![image](https://github.com/TeamHY/Astrobirth/assets/12953393/4aa678a2-97d7-408d-8356-5fd1d12675e8)
저는 오류 발생 안 되고 있습니다.

**Comment by iwt2hw** [comment]
최근 깃허브에 콤마 잘못찍고 게임 그대로 킨적 있는데 그거때문에 data 파일 깨진거였음
관련된 폴더들 전부 지우고 게임 다시 키니 나도 정상 작동됨
