### ISSUE TITLE
솔로플레이에서도 사용을 위한 모드 분리

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#221]
https://github.com/TeamHY/Astrobirth/issues/170#issue-2219513784

해당 코드 그대로 퀵옵션처럼 모드 분리

**Comment by pdom0327** [comment]
대결모드의 코드는 그대로 유지하나요?

**Comment by iwt2hw** [comment]
예-스 어차피 코드가 겹치더라도 카트리지도 해당 모드는 꺼놓고 플레이해도 돼서 상관 없습니다

**Comment by iwt2hw** [comment]
모드 이름은 대충 dark_bum_no_spider

**Comment by pdom0327** [comment]
[dark_bum_no_spider.zip](https://github.com/user-attachments/files/15538768/dark_bum_no_spider.zip)
