### ISSUE TITLE
커스텀 아이템, 커스텀 장신구 분할 작업

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#230]
✅대결모드에서만 적용되는 순정 아이템 효과는 건드리지 않습니다
✅커스텀 아이템(패시브,액티브) + 장신구(커스텀)만 분할합니다
✅분할이 끝난 이후에는 별도의 모드를 창작마당에 업로드 할 예정입니다
✅대결 모드 파일 내에서 분할된 파일들은 제거할 예정입니다
✅itemtools.xml(배열) 옮기는 작업은 따로 제가 하겠습니다 (작동 유무만 확인시켜달란 소리)

**Comment by pdom0327** [comment]
모드 이름 뭘로 할까요?

**Comment by pdom0327** [comment]
https://github.com/pdom0327/AstroItems
