### ISSUE TITLE
240605 버그 리포트

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#239]
[isaacv1.7.9b.J835-20240604-235304-16156-18656.txt](https://github.com/user-attachments/files/15568376/isaacv1.7.9b.J835-20240604-235304-16156-18656.txt)

컨티뉴 시 팅김 현상 발생
참고사항 : 에피파니, 리트리뷰션 중복 상태였음

**Comment by pdom0327** [comment]
<img width="362" alt="image" src="https://github.com/TeamHY/Astrobirth/assets/12953393/31b7828a-e1b0-4015-b06e-498718752561">
