### ISSUE TITLE
방송용 컨텐츠를 위한 모드 제작

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#245]
![KakaoTalk_20240529_223008033](https://github.com/TeamHY/Astrobirth/assets/28684443/6032827b-7357-41c9-b226-f8d1ea06024f)

✅별도 모드로 제작합니다
✅액티브 사용 시 "위 사진과 똑같이 스텟이 감소됩니다"
✅무한 액티브는 별도로 구현할 필요 없습니다 (디버그 치고 할거임)
✅다룰 모드로 설정가능하지만, 별도 모드를 만드는 이유는 고정 댓글로 "여러분들도 직접 해보실 수 있습니다!" 배포할 예정

**Comment by pdom0327** [comment]
[active-dimerit.zip](https://github.com/user-attachments/files/15741915/active-dimerit.zip)
