### ISSUE TITLE
feat: Fallen Orb(타락한 오브)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#252]
![image](https://github.com/TeamHY/Astrobirth/assets/28684443/788cec93-8471-4e65-b6d7-3427f0a019e7)

✅타락한 오브 로직을 위 사진처럼 변경합니다
└해당 아이템이 소지한 상태에서 퀄리티 0,1 등장할 경우 리롤 (사진처럼 배열은 지워져도 상관 없음)

**Comment by pdom0327** [comment]
리롤 시 배열은 지워지고 콘솔에 로그 남기도록 했습니다.
