### ISSUE TITLE
feat: ward, pink ward

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#256]
중첩 효과가 추가됩니다

✅중첩 개수만큼 보여주는 방의 개수가 늘어납니다
예: 2개 획득 시, 10칸으로 확장
✅와드와 핑크 와드는 서로 시너지 및 코드를 간섭하지 않습니다
└와드2개, 핑크 와드1개를 먹은 상태라도 15칸이 아닌 10칸이라는 소리

**Comment by pdom0327** [comment]
홀수여야 스폰방 중심이 가능해서 5 -> 9 -> 13으로 증가합니다.
