### ISSUE TITLE
Morphine - 모르핀

### ISSUE THREAD

**Issue by pdom0327** [TeamHY/Astrobirth#26]
# 효과
무적 상태 적에게 x0.25 피해를 줄 수 있게 됩니다.

## 구현 몬스터
- [x] 완전 무적 몬스터 ex) [Stoney](https://bindingofisaacrebirth.fandom.com/wiki/Fatty#Stoney) 계열

## 미구현 몬스터
- [ ] [Knight](https://bindingofisaacrebirth.fandom.com/wiki/Knight#Knight) 계열
- [ ] [Host](https://bindingofisaacrebirth.fandom.com/wiki/Host#Host) 계열

## 예외 몬스터
- [Death's Head](https://bindingofisaacrebirth.fandom.com/wiki/Death%27s_Head#Death's_Head) 계열

**Comment by pdom0327** [comment]
@iwt2hw Broken Syringe(깨진 주사기 장신구)의 황금 효과(랜덤 주사기 2개 소환)에 모르핀도 추가 할까요?

**Comment by iwt2hw** [comment]
ㅇㅇㅇㅇ깨진 주사기 황금 효과 + 주사기 파츠로도 당연 취급

**Comment by iwt2hw** [comment]
모르핀 코드 간편화를 위해 아래 항목으로 리뉴얼

1. 극 게자리 효과랑 비슷하게 몬스터에게 피해를 입힐 시 1/10 광역 효과 적용
2. 단 이 광역 효과에 보스, 빠가지는 예외로 처리
