### ISSUE TITLE
#2) newitems: Akashic Records(아카식레코드)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#261]
✅해당 아이템은 책 파츠 +3 취급합니다 (단일 아이템 하나로 책셋 가능)
✅스테이지에 책방이 있을 경우 미니맵에 표시합니다
✅방 입장 시 아래의 효과중 하나가 10% 발동됩니다 (무적책, 유도책, 밸리알의 책)
✅행운 수치 1당 5%p 증가됩니다
✅다음 판 입장 시 시작지점에 랜덤한 책 1권이 소환됩니다
✅해당 아이템은 축복 아이템으로 분류하여, 허쉬 처치 시 에이플 보상에 추가됩니다
✅책방 입장 시 미니맵을 전부 밝힙니다 (입장 시 안수즈 룬 발동으로 코딩)

![Akashic Records](https://github.com/TeamHY/Astrobirth/assets/28684443/270577df-48be-4555-adfe-861d222e82ed)

**Comment by pdom0327** [comment]
> ✅스테이지에 책방이 있을 경우 미니맵에 표시합니다
이거 빼고는 테스트 완료했습니다. 책 쓰고 스테이지 넘겨도 왜인지 책방이 안 뜨네요...
