### ISSUE TITLE
bug: 커스텀 아이템 밴&에픽빔 관련

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#265]
![image](https://github.com/TeamHY/Astrobirth/assets/28684443/f53bda7c-353b-4875-9607-9d34b5900a82)

![image](https://github.com/TeamHY/Astrobirth/assets/28684443/e4c7cb22-01ae-4c83-9e48-b225df03ced0)

![image](https://github.com/TeamHY/Astrobirth/assets/28684443/eda1b8b1-b10a-4778-a0fb-5aae88798adf)

![image](https://github.com/TeamHY/Astrobirth/assets/28684443/f3804b92-fc79-46aa-a1d7-6eb3d815238d)

✅커스텀 아이템이 밴 시스템과 에픽빔이 적용되지 않음
✅정확하지는 않지만 분리작업 이후 발생되는 현상으로 추정

**Comment by pdom0327** [comment]
원인 아직 못 찾았습니다...

**Comment by iwt2hw** [comment]
추후 에픽빔 모드 또한 대결 모드에서 제외할 예정이니 해당 작업 진행하지 않아도 됩니다!
