### ISSUE TITLE
newitems: Dunnell, the Noble Arms of Light(빛의 성검 단넬)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#271]
![Dunnell, the Noble Arms of Light](https://github.com/TeamHY/Astrobirth/assets/28684443/d321307c-de85-45a2-a2e9-1f98ede802ca)

❗아이템 효과
✅액티브 아이템이며, 획득 시 오른쪽 아래로 이동됩니다
✅해당 아이템을 소지한 상태에서 몬스터 처치 시 게이지가 찹니다 (폭주하는 죄보랑 동일)
✅사용 시 그 방 안에서만 현재 스택만큼 배수가 증가됩니다 (1스택당 배수 1% 증가, 최대 50스택)
✅용사 관련 (성전의 수견사, 일리걸 나이트) 캐릭터일경우 최대 100 스택까지 충전이 가능합니다
✅해당 아이템또한 아라메시아의 의, 금주 아라마티아 사용 시 출력되는 소리와 동일하게 출력됩니다

❗추후 변경될 수 있는 사항 (아래 요소들인 딸1깍으로 수정 가능하게 짜면 별도로 다시 밸런스 패치 요구할 확률이 많이 줄어듦)
✅1스택당 증가되는 배수 수치
✅최대 스택
✅캐릭터가 용사 관련일 경우 최대 스택

**Comment by pdom0327** [comment]
기본 포켓 액티브를 가지고 있거나 새로운 강제 포켓 액티브 아이템(Starlit Papillon)을 먹으면 어떻게 되나요?

**Comment by pdom0327** [comment]
#272 와 함께 액티브 효과는 구현했습니다. 스택 표시 위치는 아직 수정 못했습니다.

확인 결과 포켓 슬롯은 한개만 사용이 가능합니다.
3개 이상으로는 추가가 아예 안 되구요. 2개째는 그 방에서만 유지되고 나가면 사라집니다.

획득 시 포켓 위치로 이동하려면 캐릭터 고유 포켓 액티브를 제거하고 이 아이템이 들어가야 합니다. 괜찮으시다면 그렇게 진행하겠습니다.

**Comment by iwt2hw** [comment]
고유액티브가 지워지면 여러가지 생각할것도많고 밸런스도 크게 바뀝니다

✅액티브 아이템이며, 획득 시 오른쪽 아래로 이동됩니다

이 항목만 예외시켜서 부탁 드립니다
