### ISSUE TITLE
Divine Light

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#28]
예상보다 성능이 너무 좋아 요구하는 행운 수치 럭 증가
아래 의도와 맞게 잘 되어있는건지 깃 업데이트 확인. 이상이 없다면 해당 이슈 그냥 닫기 plz

기본10%, 
럭1당 10%p 증가
100% 활성화까지의 요구 행운 수치 19

**Comment by pdom0327** [comment]
기본10%,
럭1당 5%p 증가
100% 활성화까지의 요구 행운 수치 18

이렇게 되어 있습니다.
