### ISSUE TITLE
newitems: Blood Trail(블러드 트레일)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#280]
![Blood Trail](https://github.com/TeamHY/Astrobirth/assets/28684443/c0f0d7dc-a7d6-4800-a614-e1bca83750a1)

✅패시브 아이템입니다
✅해당 아이템을 소지한 상태에서 스테이지를 들어갈때마다 미트 큐브 1개를 【획득】 합니다
✅별도 제약이 없으며, 이론상 스테이지를 무한 초기화 가능할경우 미트를 무한으로 채울 수 있습니다 (시너지 악용 및 전부 의도라는뜻)

**Comment by pdom0327** [comment]
중첩 개수만큼 미트 큐브를 획득합니다.
