### ISSUE TITLE
newitems: 3 Body Problem(삼체)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#287]
![3 Body Problem](https://github.com/TeamHY/Astrobirth/assets/28684443/e8e57bb6-7701-483a-acb9-c0d9affafc8a)

✅몬스터방 입장시, 몬스터 처치 시(퀘이사와 동일하게 방당 한번만), 방 클리어 시 아래 액티브들이 각각 한번씩 작동됩니다 (한 방에서 총3회)
└리스트는 직접 https://moddingofisaac.com/docs/rep/enums/CollectibleType.html?h=collectibletype 사이트에서 보고 작성하겠습니다
└대결 모드에 존재하는 커스텀 액티브도 발동될 수 있습니다
✅해당 아이템은 특이하게도 EID 설명에 자세한 효과를 기재하지 않으며, 아래 문구만 기재합니다
└삼체문제는 예측할 수 없습니다

**Comment by pdom0327** [comment]
메이드 듀엣과 동일한 효과음 + 애니메이션 넣어봤습니다. 변경 원하시면 말씀해주세요.
