### ISSUE TITLE
newitems: 무제

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#289]
❗아이템 이름이 무제가 아니라 진짜 아직 이름과 이미지를 정하지 못했단 소리입니다
❗신규 캐릭터 루시의 기본 소지 아이템일 예정입니다
❗루시 컨셉은 액티브 아이템의 아이템을 오른쪽 포켓 자리로 옮기는 컨셉으로 하려합니다. 아래 방식을 읽고, 막히거나 문제가 있는지 컨펌 부탁드립니다

✅액티브 아이템이며, 루시에 포켓 자리에 가지고 시작합니다
✅사용 시 현재 소지중인 액티브와 포켓 자리가 체인지 됩니다
✅캐릭터가 사펑 관련(데이비드,루시)가 아닌 다른 캐릭터가 사용할 경우 아래 패널티가 적용됩니다
└사용 시 해당 아이템(무제)가 제거됩니다 (간단하게 1회용이라는 소리 루시는 계속 ㅇ액티브 바꿀 수 있고 ㅇㅇ)

**Comment by pdom0327** [comment]
포켓의 2번째로 들어간 액티브는 방을 옮기면 사라집니다. 매 프레임 저장하고 있다가 방 입장 시 재지급 하는 방법이 있긴하지만 일회용 아이템, 스택형 아이템 등과 상호작용에 여러 버그 가능성이 있습니다. 먼저 구현하고 버그를 잡는 식으로 할까요?
