### ISSUE TITLE
feat: 투표런에 별도로 사용하는 밴 모드

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#290]
현재 투표런이라는 컨텐츠중에도 별도로 아예 금지 처리한 아이템들이 존재합니다 (해당 아이템은 투표해도 나오지 않음)
이 금지아이템을 인게임중 직관적으로 확인 가능하는 기능이 필요합니다

✅등록한 아이템이 대결 모드 밴 시스템처럼 금지 애니메이션이 등장됩니다
✅대결모드처럼 스테이지 상관없이 시작방에서 애니메이션이 출력됩니다
✅단 해당 시스템은 실제 인게임에 직접적으로 배열이 제거된다던지 일체 관여하지 않습니다 (오로지 투표가 되지 않는다는걸 시각적으로 보이기 위함)
✅해당 모드는 개별적으로 제작합니다 (어차피 투표런에서만 사용할거라 대결모드 ban.lua 호환성 및 충돌은은 고려하지 않아도 됨)

**Comment by iwt2hw** [comment]
24.07.02 추가
✅해당 모드는 개별적으로 제작합니다 (투표런에선만 사용할거임 어차피)

**Comment by pdom0327** [comment]
[ban-animation.zip](https://github.com/user-attachments/files/16066486/ban-animation.zip)
