### ISSUE TITLE
newmod: 신규 컨텐츠 에덴런 시즌2, 다모런 시즌2 필요한 밴 모드

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#295]
에덴런과 다모런이 시즌2 새로운 시즌을 맞이하면서 새로운 규칙이 추가됩니다
새로운 규칙은 이전판에 사용했던 아이템들을 다음판에 사용할 수 없는 규칙입니다

✅전판 획득했던 아이템들중 n가지를 랜덤으로 추첨합니다
✅해당 컨텐츠는 에덴런과 다모런에만 사용할거라 다른 컨텐츠간에 호환성은 신경쓰지 않아도 됩니다
✅밴 시스템은 아무 보스방을 클리어 하기 전까지 초기화 되지 않습니다 (실수로 게임 눌렀을 경우 방지)

**Comment by pdom0327** [comment]
[next-ban.zip](https://github.com/user-attachments/files/16102235/next-ban.zip)
모드 껐다켜도 세이브 안 날라가네요

**Comment by pdom0327** [comment]
[next-ban.zip](https://github.com/user-attachments/files/16102504/next-ban.zip)
버그 수정
