### ISSUE TITLE
newsystem: 거울 스테이지 전용 굿트립

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#299]
밸런스 특성상 거울 스테이지를 무조건 돌아야 하는데 루즈함을 어느정도 가져옵니다
이에 맞게 전용 굿트립을 추가합니다

✅거울 2스테이지 보스방 클리어 시 아래 3개의 방들이 각각 서로서로 동선 소모없이 이동가능한 포탈이 소환됩니다
일반 황금방 <> 상점방 <> 보스방
거울 황금방 <> 상점방 <> 보스방

**Comment by pdom0327** [comment]
황금방과 보스방을 연결하는 포탈도 있나요?

**Comment by iwt2hw** [comment]
네 있습니다

황금방, 상점, 보스방 이 3가지는 서로 동선 손해없이 이동 가능한게 의도입니다
