### ISSUE TITLE
newsystem: 7~8스테이지 난이도 강화

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#300]
7~8 스테이지 (히든 제외) 난이도를 상향하려합니다
직접 구조를 건드릴 경우 과도한 시간이 소모됩니다

의도 : 해당 스테이지 입장 시 가운데 위치에 랜덤한 보스 1마리 소환

소환되는 보스의 종류는 제가 직접 넣고 싶은데 어떤 방식이 좋을까요?

일단 아이작 보스 엔티티 소환 코드로 생각중입니다

해당 모드는 아스트로버스에 적용합니다

**Comment by pdom0327** [comment]
가운데 소환하면 시작하자마자 피격 당해서 위쪽으로 올렸습니다.
```lua
-- astro/rooms/start-room-boss.lua
23.            if stage == LevelStage.STAGE4_1 then
24.                Isaac.Spawn(20, 0, 0, position, Vector(0, 0), nil)
25.            elseif stage == LevelStage.STAGE4_2 then
26.                Isaac.Spawn(20, 0, 0, position, Vector(0, 0), nil)
27.            end
```
보스 몬스터는 24, 26번줄 수정해주시면 됩니다. (20, 0, 0 -> 몬스트로)
