### ISSUE TITLE
feat: 밴관련 애니메이션 줄바꿈 기능 추가 + 밴 예외 처리

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#301]
[ban_animation.zip](https://github.com/user-attachments/files/16115170/ban_animation.zip)
[next-ban(damo).zip](https://github.com/user-attachments/files/16115171/next-ban.damo.zip)
[next-ban(eden).zip](https://github.com/user-attachments/files/16115172/next-ban.eden.zip)

설정 유지를 위해 현재 사용중인 파일 그대로 압축합니다.
해당 파일로 작업 진행합니다

✅아이템 10개가 넘어갈 경우 줄바꿈이 적용됩니다
✅밴 처리가 되지 않는 예외 시스템을 추가합니다 (nextban(eden), nextban(damo)만 적용)
└예를들어 폴라로이드, 키피스같이 퀘스트 태그가 존재하는 아이템은 밴 목록에서 제거할 예정입니다 (밴을 밴 하는 기능 ㄷㄷ)

**Comment by pdom0327** [comment]
[ban_mods.zip](https://github.com/user-attachments/files/16139095/ban_mods.zip)
