### ISSUE TITLE
newitems: WANTED: Seeker of Sinful Spoil("죄보사냥의 악마")

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#309]
✅획득 시 Sinful Spoils of Subversion - Snake Eye 한개와 소지한 아이템(인벤토리에서 제거) 2개의 아이템이 이지선다 형식으로 소환됩니다
✅해당 아이템을 소지한채로 사망 시 디아벨스타로 부활합니다
✅부활 순서의 조절할 수 있다면 1순위로 조정합니다
✅부활 순서가 어렵거나 귀찮을경우 그냥 후순위로 둬도 전혀 상관없지만 EID에 간략하게라도 표기합니다

**Comment by pdom0327** [comment]
부활 기능을 제대로 구현하려면 리펜토곤이 필요합니다.

**Comment by iwt2hw** [comment]
✅사용 시 캐릭터 즉시 변경으로는 가능할까요?

**Comment by pdom0327** [comment]
> ✅사용 시 캐릭터 즉시 변경으로는 가능할까요?

넵 가능합니다. 일회용으로 만들면 될까요?

**Comment by iwt2hw** [comment]
네 해당 효과 일회용으로 제작합니다
