### ISSUE TITLE
feat: Amplifying Mind(증폭하는 마음)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#318]
해당 아이템 효과가 캄 마인드랑 겹치는 관계로 효과가 리뉴얼 됩니다

✅마인드 바리에이션 아이템들의 증가하는 스텟의 수치가 증가됩니다
1안) +1 판정으로 처리 (예: 1캄마인드 + 1증폭하는 마음 = 2 캄마인드)
2안) 증가하는 스텟 증가량 x 2 (예 2캄마인드 + 1증폭하는 마음 = 4 캄마인드)
2개중 덜 귀찮거나 코드가 편한걸로 적용
✅코드 편리상을 위해 해당 아이템의 중복 효과는 구현하지 않습니다

**Comment by pdom0327** [comment]
기존 공격력 증가 효과는 삭제되고 모든 마인드류 아이템을 강화하는 것으로 보면 될까요?

**Comment by iwt2hw** [comment]
✅넵 기존 효과는 완전히 사라집니다
