### ISSUE TITLE
known issue: 0715 대결 방송 후 알려진 이슈

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#319]
✅칼 피스가 정상적으로 지급되지 않음 (해당 사진이 버그의 원인인지는 불명)
![KakaoTalk_20240715_232746251](https://github.com/user-attachments/assets/b9b8122e-7cf8-443f-ad1a-48ca6c88025f)

✅포탈방이 간헐적으로 이상한 방으로 이동 됨
https://youtu.be/kuBOgJwCvoE?t=11041

✅7,8스테이지 일반 모든방에 등장해야하는 보스들이 시작방에만 나오는 현상

✅밴시스템이 정상적으로 작동되지 않는 현상
이 부분에 대해서 정확한 원인은 아직 찾지 못함

**Comment by pdom0327** [comment]
> ✅칼 피스가 정상적으로 지급되지 않음 (해당 사진이 버그의 원인인지는 불명) ![KakaoTalk_20240715_232746251](https://private-user-images.githubusercontent.com/28684443/349047190-b9b8122e-7cf8-443f-ad1a-48ca6c88025f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNDk3NTEsIm5iZiI6MTcyMTE0OTQ1MSwicGF0aCI6Ii8yODY4NDQ0My8zNDkwNDcxOTAtYjliODEyMmUtN2NmOC00NDNmLWFkMWEtNDhjYTZjODgwMjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE3MDQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NjEyMGRjODc1NWE1ZjlkNmIzNThiMDg3NTVhMmY4ZGE4Y2Y3YjBkZWM0MWQ2ZWQyZWU2NzFlOTA3NWNkZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l1hCIrzbkMiebactXaPD6CxAVvq4oSiEgZVydpp_T8w)

맨 위쪽의 에러 메세지가 필요합니다. 다음에 발생 시 로그 파일 전체 업로드 부탁드리겠습니다!

**Comment by pdom0327** [comment]
> ✅7,8스테이지 일반 모든방에 등장해야하는 보스들이 시작방에만 나오는 현상

업데이트 했습니다.

**Comment by iwt2hw** [comment]
✅포탈방이 간헐적으로 이상한 방으로 이동 됨
https://youtu.be/kuBOgJwCvoE?t=11041

제외한 나머지 해결 완료
