### ISSUE TITLE
밴 초기화 관련

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#320]
대결에서는 이전 대결러 사용하던 아이템들을 지워야하는데 매판 끝나고 1스테이지 보스잡는 행위가 생각보다 방송에서 많이 귀찮고 늘어짐

✅대결 밴 초기화 시점 기존처럼 아예 리셋으로 롤백

**Comment by pdom0327** [comment]
초기화 콘솔 명령어를 추가하는건 어떨까요?
