### ISSUE TITLE
delete: 아스트로 버그에 내장된 에픽빔 시스템 제거

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#321]
✅대결 모드 자체 내장된 에픽빔 시스템을 제거합니다

에픽빔 개별 모드로만 사용할 생각입니다
대결모드의 경우 제가 직접 넣어줘야하는데 장기적으로 봤을 때, 이중으로 작업해야하고 퀄리티로만 건드리는게 호환성 및 버그로도 좋을 거 같습니다

심지어 가끔 버그 로그에 에픽빔 관련으로도 등장되기 때문에 대결모드에 에픽빔 시스템은 제거합니다

**Comment by pdom0327** [comment]
[epic beam_3172185950.zip](https://github.com/user-attachments/files/16319058/epic.beam_3172185950.zip)
대결 모드랑 호환 문제는 아니고 버그 수정 파일입니다.
