### ISSUE TITLE
bug: 다모클래스 피격 유무 처리 관련

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#322]
![image](https://github.com/user-attachments/assets/31441476-74f5-4119-9ae6-329fac9e238a)

[damorun_2882462930.zip](https://github.com/user-attachments/files/16289782/damorun_2882462930.zip)

✅기존 기능들은 전부 유지한 채 특정 단축키를 누를 경우 빨간불을 온 / 오프 가능하게 변경합니다
✅모드 컨피그 메뉴는 지원하지 않아도 됩니다 (진짜 필요없음 시간 안써도 됨)
✅해당 모드 제작자는 하트비트님입니다. 작업 중 이슈 발생 시 저를 통해서 물어봐도 되고, 직접 사무소에서 호출 후 질문하셔도 됩니다

**Comment by pdom0327** [comment]
[damo indicator_2959032300.zip](https://github.com/user-attachments/files/16318935/damo.indicator_2959032300.zip)

올려주신 모드랑은 다른 모드입니다.
