### ISSUE TITLE
feat: 대결 모드 아이작 캐릭터 컨셉안 관련

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#324]
✅스테이지 시작 시 소지한 액티브가 제거됩니다
✅스테이지 진입 시 리스트에 적힌 아이템들중 2가지가 이지선다로 등장합니다
└등장되는 리스트에는 스다, 스핀업, 미러주사위 등 주사위 관련된것들이 등장할 예정입니다. 제가 직접 리스트를 수정할 수 있게 솔라시스템과 동일하게 코딩합니다
✅상기 효과는 캐릭터가 아이작일경우 활성화 됩니다 (생득권 아자젤처럼 다른 캐릭터일때도 발동되는 버그 조심)

**Comment by pdom0327** [comment]
소지한 액티브가 다이스 계열일 경우만 지워야 할까요? 아니면 무조건 지워야할까요? 지금은 일단 다이스 계열만 지우도록 했습니다.
