### ISSUE TITLE
feat: 퀵옵션 모드 신기능

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#336]
[240723Q_Option.zip](https://github.com/user-attachments/files/16343412/240723Q_Option.zip)

![KakaoTalk_20240723_123947668](https://github.com/user-attachments/assets/49652ce9-4d59-4400-ad18-37d055048b18)
![KakaoTalk_20240723_124003613](https://github.com/user-attachments/assets/ae52c738-41e6-4756-aa9e-37634725ec57)

✅아래 조건에 따라 HudOffset 수치를 조절할 수 있는 기능을 추가합니다
└현재 방이 방 클리어 상태일 경우
└현재 방이 방 클리어가 되지 않은 상태일 경우
✅아래 조건에 따라 MapOpacity 수치를 조절할 수 있는 기능을 추가합니다
└현재 방이 방 클리어 상태일 경우
└현재 방이 방 클리어가 되지 않은 상태일 경우

✅수치는 직접 설정해서 사용하겠습니다

**Comment by pdom0327** [comment]
[240723Q_Option.zip](https://github.com/user-attachments/files/16345282/240723Q_Option.zip)
