### ISSUE TITLE
newmods: 사용 시 인게임에서 버거가 돌아가는 모드

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#340]
현재 투표런, 에덴런, 다모런 등 실패 시 시청자들에게 버거의 개수를 카트리지를 사용해서 하고 있습니다
유튜브 영상 및 편리성을 위해 인게임에 보스 룰렛 기능처럼 버거 개수를 추첨합니다

✅추첨 하는 버거의 개수 2~5 입니다
✅버거의 개수를 직관적으로 확인할 수 있어야 합니다 (예 : 버거 이미지 하나에 x 5 or 뭉쳐있는 버거의 이미지 5개)
✅버거의 이미지는 싸이버거를 굳이 사용하지 않아도 됩니다
✅별도 모드로 제작합니다
✅핫키 : 9번

**Comment by iwt2hw** [comment]
개인적으로 지금 보스 룰렛 시스템이랑 완전 동일한데 보스 이미지만 버거 였으면 괜찮으면 함

**Comment by pdom0327** [comment]
[burger-roulette.zip](https://github.com/user-attachments/files/16413774/burger-roulette.zip)
