### ISSUE TITLE
bug : 특정 아이템 사용 시, 소리가 누락되는 현상

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#341]
-최근 분리작업을 하면서 경로 문제로 아스트로버스에 적용해놨던 소리(이터널과 소울 하트를 노농 버전으로 바꿔주는 파일) 적용되지 않는 현상이 발생 했었음

-해당 현상 원인이 로컬 경로 문제(리소스\sfx) 사용해서 생긴 문제로 생각하고, 아스트로버스(아이템) 모드에 존재하는 sfx 파일들을 resources -> content 옮기는 작업을 진행했음
└(당연 알겠지만 모드 만들 때 로컬 경로에서 수정하면 우선 순위가 제일 높은거 하나만 적용됨)

-아스트로 아이템 안에 sfx 파일들을 content 옮긴결과 아스트로버스 사운드들은 잘 출력 됐음

-상기 작업 이후 이유에서인지 커스텀 사운드들이 출력되지 않음 (아스트로버스 끄고 해도 그대로 인걸로 봐서 아스트로아이템 경로 등의 문제로 예상됨

-신기하게도 c822 죄보합전은 정상적으로 출력됨

![image](https://github.com/user-attachments/assets/a72d4082-0be0-4efd-914f-0e59acea2640)

-출력되지 않는 아이템
└마이문, 아라마시아 의, 금주 아라마티아, 폭주하는 죄보 4개는 발동되지 않음

✅단순 경로 문제면 내가 해결했을텐데, 뭔가 코딩적으로 문제있는거 같아 찾다가 그냥 깃허브 버그에 글남김

**Comment by pdom0327** [comment]
content 안에 넣으면 작동하지 않습니다. resources에 넣어야 합니다.
현재 저는 `c882`도 소리가 나지 않습니다.
