### ISSUE TITLE
newcharacter : Rachel(라헬)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#344]
✅레아 캐릭터의 알트폼입니다

[rachel.zip](https://github.com/user-attachments/files/16401963/rachel.zip)

**Comment by pdom0327** [comment]
![image](https://github.com/user-attachments/assets/d4ac3d58-17b4-4a7e-8dec-760f414d1d39)
라헬 해당 이미지가 필요합니다. 나머지는 적용되었습니다.
