### ISSUE TITLE
보스방 애니메이션 제거 파일을 AstroItems > Astrobirth로 변경

### ISSUE THREAD

**Issue by kohashiwakaba** [TeamHY/Astrobirth#349]
- 보스방 애니메이션 파일의 경우 StageAPI 계열 모드에서도 사용됨 (Fiend Folio, Fall from Grace 등 스테이지 및 보스 추가 모드)
- 보스방 애니메이션 제거 시 StageAPI에서 해당 애니메이션을 불러오지 못해 100%의 확률로 튕김

**Comment by pdom0327** [comment]
양쪽에 애니메이션 파일 다 있어서 AstroItems에서 삭제 했습니다.
