### ISSUE TITLE
곱연산 공식 오류

### ISSUE THREAD

**Issue by pdom0327** [TeamHY/Astrobirth#351]
아이템 중첩 시 곱연산 공식이 잘못되어 있습니다.
제곱 연산이 들어가 수치가 1보다 작을 경우 아이템 갯수가 늘어날 수록 오히려 줄어들고 있으므로 공식을 변경해야 합니다.

- [x] GALACTIC_MEDAL_OF_VALOR
- [x] PAVO
- [x] SAGITTARIUS_EX
- [x] THREE_BODY_PROBLEM

**Comment by pdom0327** [comment]
![image](https://github.com/user-attachments/assets/848eb63c-83bb-4944-b112-45904dd64b13)

**Comment by makabeP** [comment]
공작자리랑 초사수자리도 문제 있어요
