### ISSUE TITLE
feat: 금고방 관련 컨셉

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#355]
금고방을 보너스 컨셉으로 바꾸려 합니다
브금도 아예 쿠키런 보너스 타임 출력되게 할거임
![image](https://github.com/user-attachments/assets/9f0643ff-0487-4963-8b95-cf63635a1c3e)

✅금고방 입장 시 일정 시간 후 방 안에 픽업 전부 제거 (미스트 적용 유무와 상관 없이 모든 금고방에 적용)
✅테이블은 지워지지 않음
✅일부 방에는 mist 기능을 적용할 예정
✅방 입장 시 시각적으로 시간을 알 수 있는 요소 추가 (1안부터 추진, 문제가 있을 경우 2안 or 본인이 직접 구상한거 해도됨)
1안) 보스 게이지바가 조금씩 줄어들면서 알 수 있는 형식
2안) 투표런이나 카그 랭크업 시스템처럼 그냥 대강 알수만 있는 형식

❗추후 변경될 수 있는 사항
픽업이 삭제되기 전까지의 시간

**Comment by pdom0327** [comment]
테이블이 콜렉터블 아이템 말씀이신가요?

**Comment by iwt2hw** [comment]
ㅇㅇ 패시브, 액티브 = 테이블(컬렉티브)
