### ISSUE TITLE
feat: 자석 모드 새로운 기능

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#356]
해금런 컨텐츠중에 자석 모드 실수 사용 방지를 위해 수시로 온오프를 합니다

매번 설정창 들어가는게 심각할정도로 흐름이 깨집니다
[quickpick_3009418128.zip](https://github.com/user-attachments/files/16496388/quickpick_3009418128.zip)

✅퀵옵션처럼 단축키 하나로 온 / 오프 상태를 조절할 수 있도록변경
✅모드 컨피그 모드로 해당키 설정하는 기능은 없어도 됨 (루아로만 바꿀 수 있으면 됨)
✅변경 시 사운드로 온 / 오프 상태를 알 수 있게 노래 추가
└온 = specialsummon
└오프 = destroyed
✅온 = 9
✅오프 = 0

**Comment by pdom0327** [comment]
[quickpick_on_off.zip](https://github.com/user-attachments/files/16500338/quickpick_on_off.zip)
