### ISSUE TITLE
블러드 오스, 잇 허츠 추가 효과

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#36]
1. 블러드 오스 : 획득시 공격력(고정) +1.8 증가. 현재 소지중인 하트 한칸당 공격력 0.18 감소
![980](https://github.com/TeamHY/Astrobirth/assets/28684443/004687df-f5fb-422e-bf0c-62726c651887)
2. 잇 허츠 : 배수 1.3배 증가
![981](https://github.com/TeamHY/Astrobirth/assets/28684443/78febd4a-0dfd-452f-8d53-f99d91e4143b)

**Comment by pdom0327** [comment]
1. 하트가 빨강, 소울, 블랙, 뼈 모두 포함인가요?

**Comment by iwt2hw** [comment]
A : ㅇㅇ 모든 하트 포함
