### ISSUE TITLE
bug: 공작자리 획득 시 마더보스에서 팅기는 현상

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#361]
![image](https://github.com/user-attachments/assets/219316d0-7cb2-44a5-bb8f-90829eda85b4)

[isaacv1.7.9b.J835-20240808-062213-18792-11044.dmp](https://github.com/user-attachments/files/16534788/isaacv1.7.9b.J835-20240808-062213-18792-11044.dmp)
[isaacv1.7.9b.J835-20240808-062213-18792-11044.txt](https://github.com/user-attachments/files/16534789/isaacv1.7.9b.J835-20240808-062213-18792-11044.txt)
[log.txt](https://github.com/user-attachments/files/16534790/log.txt)

**Comment by pdom0327** [comment]
Pavo가 없어도 발생하는 것 같습니다.

**Comment by pdom0327** [comment]
Astrobirth 내에 있는 룸 파일 삭제하니 정상 작동합니다.

**Comment by iwt2hw** [comment]
로컬경로? 커스텀경로? 정확히 어떤 파일? 근데 일단 뭐가 원인인지 예측은 감

**Comment by iwt2hw** [comment]
해결 완료

공작 자리와는 관련 없었음

그냥 순수 내 경로 실수
