### ISSUE TITLE
newtitems: Sacred Dice(성스러운 주사위)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#364]
✅액티브 아이템입니다
✅사용 시 아래 효과가 적용됩니다
└리롤 기능이 발동됩니다
└해당 액티브를 사용하여 리롤 시 0,1 퀄리티는 등장하지 않으며, 2 퀄리티 등장 시 20% 확률로 다시 리롤이 발동됩니다
✅세부 설정 및 이미지는 추후 직접 추가하겠음

기본적으로 타락한 오브와 같은 방식으로 코딩합니다. 단 해당 방식보다 더 편한거나 다른 방식을 차용했을경우 해당 깃허브 댓글이나 파일안에 방식을 기재합니다

**Comment by pdom0327** [comment]
오브랑 완전히 같은 방식을 쓸 순 없어서 조금 다르지만 기능적으로는 큰 차이 없습니다.
오리지널 다이스랑 다르게 무조건 그 방 배열을 따라갑니다.

**Comment by pdom0327** [comment]
가장 최근의 방 배열 가져올 수도 있는데 그렇게 변경할까요?
