### ISSUE TITLE
newtitems: Forbidden Dice(금지된 주사위)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#365]
✅액티브 아이템입니다
✅사용 시 아래 효과가 적용됩니다
└액티브 아이템 등장 시, 재 리롤되며 패시브 아이템이 등장할때까지 리롤 (6dice + No! 합쳐진 버전이라 생각하면 편함)
✅세부 설정 및 이미지는 추후 직접 추가하겠음

기본적으로 타락한 오브와 같은 방식으로 코딩합니다. 단 해당 방식보다 더 편한거나 다른 방식을 차용했을경우 해당 깃허브 댓글이나 파일안에 방식을 기재합니다

**Comment by pdom0327** [comment]
성스러운 주사위와 같은 매커니즘입니다.
