### ISSUE TITLE
bug: 금고방에서 자석 모드가 활성화되는 버그

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#368]
![image](https://github.com/user-attachments/assets/a4cf5a09-9f61-4454-89dd-41d031bf6ca8)

![image](https://github.com/user-attachments/assets/9bcc654f-9314-465c-801f-a1e7c959ecaf)

#356 

최신 버전 자석모드로 진행하였습니다

**Comment by pdom0327** [comment]
카톡으로 드렸던 버전이 더 최신 버전 자석모드였습니다. 죄송합니다. #372 에 함께 업로드 하겠습니다.
