### ISSUE TITLE
feat: 1스테이지 시작방에서 에픽빔 작동하지 않도록 변경

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#370]
[epic beam.zip](https://github.com/user-attachments/files/16621484/epic.beam.zip)

✅아이작 및 막달린 캐릭의 경우 시작 시 3,4 퀄리티가 등장하는데 귀테러 및 ㅈ망겜같아 보기 좋지 않습니다

**Comment by iwt2hw** [comment]
추가) 모든 시작방이 아닌 1스테이지 시작방

**Comment by pdom0327** [comment]
[epic.beam-240820.zip](https://github.com/user-attachments/files/16669017/epic.beam-240820.zip)
