### ISSUE TITLE
feat: 자석모드(퀵픽)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#372]
[quickpick_3009418128.zip](https://github.com/user-attachments/files/16647852/quickpick_3009418128.zip)

✅아스트로버스, 아스트로룸, 아스트로아이템 3개의 모드중 【하나라도 구독】 되어있어야 정상적으로 사용 가능하도록 변경

**Comment by pdom0327** [comment]
[astro-rooms-main.zip](https://github.com/user-attachments/files/16669073/astro-rooms-main.zip)
해당 main.lua 파일을 astro-rooms 모드에 넣어야합니다.

[quickpick_240809.zip](https://github.com/user-attachments/files/16669103/quickpick_240809.zip)
모드 상관없이 사용할 수 있는 버전

[quickpick-240820-only-astro.zip](https://github.com/user-attachments/files/16669100/quickpick-240820-only-astro.zip)
Astro 시리즈 적용 시에만 사용 할 수 있는 버전
