### ISSUE TITLE
feat: 성당, 지옥 보스 클리어 시 진행 아이템 지급

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#376]
![image](https://github.com/user-attachments/assets/234ab5e6-c185-4b82-9cb1-5f2c5aee3632)

✅성당 보스방 클리어 시 캐릭터 인벤토리에 직접 "폴라로이드를 지급합니다
✅지옥 보스방 클리어 시 캐릭터에게 인벤토리에 직접 "네거티브"를 지급합니다

**Comment by pdom0327** [comment]
칼피스, 키피스와 동일하게 소지하고 있지 않을 때만 지급하도록 했습니다. 1P만 체크하기 때문에 예를들어 2P 캐릭터가 폴라를 소지하고 있으면 1P에게 폴라가 또 지급됩니다.
