### ISSUE TITLE
newcharacter : Nayuta(나유타)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#379]
![character select menu7](https://github.com/user-attachments/assets/66440d7f-17fb-4409-b5fa-3b5407180a29)
![character_stateless](https://github.com/user-attachments/assets/94ae9e2c-e0bc-4469-82cd-12e9d7326f91)
![character_stateless_hair](https://github.com/user-attachments/assets/6b840602-e97a-48fb-af8d-91f5eba38724)

✅캐릭터 or 방 전쳉에 모래가 떨어지는 효과 (직접 구현해도 되고, 일단 상훈이한테 전달 해놓은 상태임)

**Comment by pdom0327** [comment]
스텔라의 알트캐인가요? 별도의 캐인가요? 모래 효과는 어떤건지 잘 모르겠습니다.

**Comment by iwt2hw** [comment]
모래 효과는 상훈이한테 받아서 전달해드리겠습니다. 이사 때문에 모드 신경 쓸 여유가 없네요 일단 신경 안쓰셔도 됩니다 

저번처럼 깡통이어도 진행만 가능하게만 해주세요
