### ISSUE TITLE
feat: EZ Mode

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#380]
✅낙제 장신구 사라지지 않도록 변경
└현재 버전 : 에이플, 낙제 둘 다 후반부 피격 시 삭제됨
└요청 사항 : 에이플은 사라지되, 낙제는 사라지지 않도록 변경

**Comment by pdom0327** [comment]
그럼 이지 모드를 후반 스테이지에서 제거하는게 아니라 무효과로 만들어야하나요?
