### ISSUE TITLE
newmods: 체력을 인게임내에서 조절할 수 있는 모드

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#382]
모드 이름 : 대충 보스 체력을 조절할 수 있다는 영어 명칭 모드

❗기본적인 모드 기능❗
✅체스트, 램, 메가사탄, 허쉬, 데릴리움, 도그마, 비스트 체력을 인게임내에서 조절합니다
✅각 보스마다 체력을 노말, 하드, ,슈퍼하드, 루나틱, 임파서블 5단계로 조절할 수 있습니다
✅노말 : 순정 체력
✅하드 : 기존 체력 두배
✅슈퍼하드 : 50만
✅루나틱 : 1천
✅임파서블 : 1억

❗모드 컨피그로 조절할 수 있는 사항❗
✅개별 보스의 체력
└예시 : 데릴리움만 루나틱(1천 설정)
✅일괄 체력 수정
└예시 : 데릴리움만 루나틱 상태에서, 모드 자체를 노말(순정 체력)로 바꾸면 설정해놓은 모든 보스들의 프리셋 상태가 노말(순정) 체력 상태로 돌아감

**Comment by pdom0327** [comment]
메가 사탄, 도그마 2페이즈가 잘 안 되네요... 방법 찾아보겠습니다.

**Comment by iwt2hw** [comment]
✅평소하던 50만 컨텐츠와 다르게 성당, 지옥 보스는 상정하지 않습니다
└예시: 체스트 루나틱) 시체 보스만 1천

**Comment by iwt2hw** [comment]
✅허쉬와 데릴리움의 경우 체력을 분배하지 않습니다
[예시] 슈퍼하드(50만) 상태
└기존 : 허쉬 25만, 데리리움(50만)
└변경 : 허쉬 50만, 데릴리움(50만)

**Comment by pdom0327** [comment]
[boss-health-modifier.zip](https://github.com/user-attachments/files/16759296/boss-health-modifier.zip)
