### ISSUE TITLE
feat: boss-health-modifier

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#386]
✅누락된 보스와 신규 보스 3종을 추가합니다 (마더,울트라 그리디어)

✅페이즈가 존재하는 보스들은 설정된 체력을 분할합니다 (예시, 체력이 1000 이라고 가정할 경우 500 씩 설정)
└마더(1페이즈/2페이즈)
└메가사탄(1페이즈/2페이즈)
└램(기본램/램베이비)
└울트라 그리드 / 울트라 그리디어
└도그마(티비) / 도그마(티비분리후)
상기 기재한 보스외에 다른 보스들은 일괄 적용 시킵니다
✅신규 난이도 인세인이 추가됩니다
└인세인은 기존 임파서블을 대체합니다 (1억)
└임파서블은 기존 1억에서 10억으로 변경됩니다

✅게임 재 시작 시 모든 세팅을 노말 상태로 되돌립니다

✅단축키를 활용해서 일괄적으로 난이도를 설정할 수 있는 기능을 새로 추가합니다 (기존 보스룰렛과 비슷한 결이라고 생각하시면 됩니다
└예시1 : 난이도가 슈퍼하드일경우 아래와 같이 표시
Boss HP : SuperHard(500K)
└예시2 : 난이도가 인세인일경우 아래와 같이 표시
Boss HP : Insane(100M)
└색상은 보스 룰렛과 같은 자주색을 사용
![image](https://github.com/user-attachments/assets/00393a18-5fa1-4ae0-9c12-2f04a0f86e20)

✅체력 수치를 직관적으로 확인할 수 있도록 난이도 명칭을 아래와 같이 변경합니다
└Normal
└Hard(x2)
└SuperHard(500K) --50만
└Lunatic(10M) --1000만
└SKT(1557) -- 1557만
└Insane(100M) --1억
└Impossible(1B) --10억
└Savage(1T) --1조

![image](https://github.com/user-attachments/assets/e9a1c0ff-c908-46bf-8233-42d67beca78d)

❗추후 변경될 수 있는 사항 및 모드 컨피그
✅5번 항목 단축키 변경은 추후 변경할 수 있도록 코딩합니다 (모드 컨피그 지원X, 루아로만 수정 가능하도록)
✅폰트는 룸네임 및 보스룰렛과 동일한 폰트를 사용하며, 보스 룰렛처럼 좌표 이동을 가능하도록 지원합니다

**Comment by pdom0327** [comment]
[boss-health-modifier-240902.zip](https://github.com/user-attachments/files/16830488/boss-health-modifier-240902.zip)
다운로드 하시면 삭제하겠습니다.

**Comment by iwt2hw** [comment]
다운 완료

**Comment by pdom0327** [comment]
[boss-health-modifier-240902V2.zip](https://github.com/user-attachments/files/16830917/boss-health-modifier-240902V2.zip)
1557 추가했습니다.

**Comment by iwt2hw** [comment]
다운 완료
