### ISSUE TITLE
feat: 장신구 활용도를 위한 신규 기능

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#389]
에이플 이전에 장신구가 나올경우 활용이 불가능한 구조를 개선합니다

✅기능성이라 아스트로버스에 코딩합니다
✅아래 상황을 모두 충족시킬경우, 장신구 흡수 액티브(스맬터) 발동됩니다
└현재 스테이지가 히든 스테이지2 일경우에만 발동됩니다 (일반 2스테이지에서는 발동 ㄴㄴ)
└에이플 및 낙제를 소지하고 있지 않을경우에만 발동됩니다 (에이플 및 낙제 자동흡수 밸런스 목적 ㅇㅇ)

예를들어 바포메트를 가지고 있는 상태라면 바포메트를 흡수할지,
에이플 컨트롤을해서 매직볼 보상을 먹을 지 유저의 선택지가 늘어나는것이 의도입니다

**Comment by pdom0327** [comment]
1. 히든 2스테이지 보스방 클리어 시 발동인가요?
2. 거울 차원에서는 발동하지 않나요?

**Comment by iwt2hw** [comment]
1. 네 히든 2 스테이지에서『만』 발동됩니다
2. 거울 차원에서 발동됩니다
└애초에 에이플 or 낙제를 들고, 에이플 추가 방 보상을 먹을것이냐 vs 에이플 소지 보상을 포기하고, 차라리 소지중인 장신구를 흡수할것이냐

이것이 의도이기때문에 발동해도 상관 없습니다
본문에도 나와있지만 에이플 및 낙제가 소지중인 상태(흡수도 포함) 일 경우에는 발동을 하지 않습니다
