### ISSUE TITLE
mod: 아이템 리뉴얼 이미지 글리치드 크라운 최적화 관련

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#391]
https://steamcommunity.com/sharedfiles/filedetails/?id=3097622385

**해당 모드를 적용된 상태에서 폭식가, 소울오브아이작, 글리치드 크라운류 소지했을경우, fps 과도하게 떨어지는 현상을 완화하기위해 이미지 기능을 모드를 인게임중 아예 비활성화 합니다**

✅아래 항목중 하나라도 해당될 경우 OFF (게임 재 시작 시 다시 ON)
└글리치드 크라운을 소지한 상태일 경우
└폭식가를 소지한 상태일 경우
└캐릭터가 아이작인 상태에서 생득권이 적용중일 경우
└캐릭터가 알트 아이작일 경우

✅아래와 같은 상황에서 모드를 다시 ON 시키는 기능은 코드 최적화 및 버그 고려성을 최우선으로 패치합니다
1안) 글리치드 크라운을 획득해서 모드가 OFF 됐고, 4각등 사유로 해당 아이템이 제거됐을경우 다시 해당 모드를 활성화
2안) 위와 같은 상황에서 다시 글리치드 크라운이 사라지더라도 다음 게임 시작 시 까지 계속 OFF

**Comment by pdom0327** [comment]
[!rebirth vectorized redone-240903.zip](https://github.com/user-attachments/files/16848659/rebirth.vectorized.redone-240903.zip)

1안 입니다.
