### ISSUE TITLE
feat: 투표런 밴 기능과 애니메이션 관련

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#396]
현재 투표런은 방송을 위해 과도한 오버밸런스 아이템을 금지로 처리하고 있습니다
랜덤표 기능이 추가된 이후로 의미없는 아이템(피맥,사거리,스피드류)들의 등장 빈도가 많이 증가하였습니다
이러한 현상을 해소하기 위해, 상기 기재한 의미 없는 아이템을 대거 금지처리할 예정입니다
이 경우 시작방에서 과도한 금지아이템 이미지가 출력되어 미관상 굉장히 보기 안좋아집니다

일단 아래 방법은 제가 따로 생각해놓은 방법이며, 더 좋은 방법 코맨트나 개인 연락 부탁드립니다

✅시작방에서 애니메이션이 출력되는 밴, 애니메이션이 출력되지 않는 밴 분할 (결국 둘 다 밴으로써 역할은 적용됨)
✅밴 방법은 지금처럼 아이템 코드가 아닌 숫자로 적용 (아이템 대량으로 넣을거라 코드면 작업 효율 떨어짐)

일단 혹시 몰라 제 기준 세팅 최신버전인 투표 모드와, 밴 애니메이션 2개 같이 업로드 해놓겠습니다
[ban_animation(240901).zip](https://github.com/user-attachments/files/16828115/ban_animation.240901.zip)
[HYItemVote_4(240901).zip](https://github.com/user-attachments/files/16828116/HYItemVote_4.240901.zip)

**Comment by pdom0327** [comment]
[HYItemVote_4-240903.zip](https://github.com/user-attachments/files/16848216/HYItemVote_4-240903.zip)

HYIV.secretBanList 추가 했습니다.
