### ISSUE TITLE
feat: 엄마발 세트 리뉴얼 관련 및 설정 관련 질문

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#397]
엄마세트를 기존 효과를 지우고 "일정 시간마다 엄마발 소환(정확히는 하이프리스티스 카드 발동) 설정하려고 합니다

자해 방지를 위해 몬스터가 있는 방에서만 발동시키게 설정하긴할건데, 엄마발 피격에 대한 면역이 설정이 가능한지 궁금합니다

별개로 위 효과를 사용한 아이템도 추후 개발할 수 있습니다

**Comment by pdom0327** [comment]
![image](https://github.com/user-attachments/assets/649abfc0-0b8a-43c8-85bb-05c1807be70d)
