### ISSUE TITLE
feat: epic beam + 퀵픽

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#400]
✅퀵픽 모드에 에픽빔 기능을 추가합니다
✅퀵픽 활성화 시 에픽빔이 출력되도록 설정합니다

**Comment by pdom0327** [comment]
[quickpick-240906.zip](https://github.com/user-attachments/files/16906065/quickpick-240906.zip)

모드 이름은 일단 변경하지 않았습니다.
