### ISSUE TITLE
#2 newmod: 신규 컨텐츠 도박런을 위한 새로운 모드

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#401]
해당 모드를 적용한 상태에서 입력한 키에 따라서 아래 효과가 발동됩니다
✅F6 = 사용 시 이터널 다이스를 발동합니다
✅F7 = 사용 시 도박 코인이 발동됩니다
✅루아에서 직접 키를 변경할 수 있도록 코딩합니다 (모드컨피그 지원안해도 괜찮음)

**Comment by iwt2hw** [comment]
더 좋은 방법이 생겨서 본문 자체 모든글을 재작성하였습니다

**Comment by pdom0327** [comment]
[gambling_run.zip](https://github.com/user-attachments/files/16917244/gambling_run.zip)
