### ISSUE TITLE
로컬 경로에서 태그를 건드리지않고, 리롤 방지가 가능합니까?

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#402]
예를들어 도박런에서 알트 에덴으로 플레이할경우 소지중인 이터널 다이스와 도박 코인이 피격 시 리롤될경우 다시 꺼내야되고 밸런스 및 여러가지 문제가 발생할 수 있습니다

퀘스트아이템처럼 태그에 노리롤 붙이는 방법도 있지만 이 경우 로컬 item.xml 건드려야해서 호환 및 충돌 이슈가 발생할 수 있어서 로컬 파일을 건드리지않고 리롤되지않는게 가능한지 궁금합니다

**Comment by pdom0327** [comment]
아이템이 리롤된다면 재지급 하는 방식으로 해결해야 할듯합니다. 패시브 아이템에는 적용하기 어렵습니다.

**Comment by pdom0327** [comment]
오 괜찮은 방법 같습니다.

**Comment by kohashiwakaba** [comment]
아예 도박코인, 이다 발동을 특정 키에 할당하는 것도 좋습니다. 이 경우 획득한 액티브도 온전히 사용 가능할 수 있습니다.
