### ISSUE TITLE
feat: 겜블런에 배열 지우는 기능 추가

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#414]
겜블런에 경우 글리치드 크라운, 빛나는 모래시계등 방송적으로 좋지않아 등장하는거 자체를 막으려고 합니다 (왜 안쓰나요, 저거 쓰면 무한으로 되지 않나요? 등 방지)

✅겜블런에 빛나는 모래시계, 글리치드 크라운을 등장하지 않도록 합니다
└아이템 등장 시 리롤하는 방식, 게임 시작 시 아예 배열을 지우는 방식 2개다 상관 없습니다.
✅상기 기재한 모래시계와 글리치드 크라운 외에도 금지아이템이 추가될 수 있을 수 있으니, 대결모드처럼 루아 아이템 사이트에서 직접 제가 수정할 수 있도록 코딩합니다 

[gambling_run.zip](https://github.com/user-attachments/files/17034787/gambling_run.zip)

**Comment by pdom0327** [comment]
[gambling_run-240920.zip](https://github.com/user-attachments/files/17065063/gambling_run-240920.zip)
배열 제거 입니다.
