### ISSUE TITLE
feat: 파리셋 관련 모드 분리

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#421]
파리 배속이 단순 성능을 넘어서 최적화에도 이렇게까지 최적화 및 성능에 도움 될줄 몰라서
해당 모드 분리하기로 했습니다 (이중작업 ㅈㅅㅈㅅ..)

✅해당 모드 적용 상태일 경우 파리 배속이 100% 증가 (디폴트 세팅)
✅게임 재 시작 시 디폴트 세팅(100%)으로 초기화
✅모드 컨피그 모드를 통하여 3단계로 조절 가능 (기본, 100%, 200%)
✅자주 바꾸는 것도 아닐거라 단축키 지원은 필요 없음
✅기존 아스트로버스에 파리 배속 관련 옵션은 제거 (해당 모드 하나로 전부 관리할 생각)
✅아스트로아이템에 섬망의 구피는 다시 하얀파리 소환만 있는 상태로 롤백합니다 (어차피 효과 리뉴얼 예정)

모드 명칭 : 대충 영어로 플라이 속도 어쩌구

**Comment by pdom0327** [comment]
[fast-fly.zip](https://github.com/user-attachments/files/17089844/fast-fly.zip)
