### ISSUE TITLE
newmod: 황금 아이템 모드 #2

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#425]
✅패시브 아이템이 등장 시 + 리롤 시 해당 아이템에 설정한 확률에 한해서 황금 효과를 적용합니다
✅획득 시, 아이템 1개가 더 들어옵니다
✅현재 에피파니 모드가 적용중일 경우 해당 모드는 사실상 모드가 꺼진 상태로 취급합니다 (에피파니 모드와의 호환성 고려)

비고 (첫번째일수록 우선 순위이지만 굳이 안해도 됨 또한 더 좋은 방법이 있다면 그 방법으로 의논 언제든 환영)

-황금 아이템 리롤 시 황금 상태의 유무 처리
└1안 : 리롤 후, 패시브일경우 황금 상태 유지, 액티브가 됐을 경우 황금 상태 해제
└2안 : 1안이 버그 및 어려울 경우 그냥 리롤 시 황금 상태 아예 해제

-복시를 이용해서 복사에 성공했을 경우
└1안 : 황금 상태를 유지해서 복사
└2안 : 1안이 버그 및 어려울 경우 황금 상태를 제거 후 복사
└3안 : 2안까지 어려울 경우 황금 아이템은 복사를 받지 않도록 설정

❗추후 직접 조절할 수도 있는 요소 (최대한 반복 작업 방지용)
✅황금 아이템의 등장 확률

**Comment by iwt2hw** [comment]
#2 

❗추후 직접 조절할 수도 있는 요소 (최대한 반복 작업 방지용)
✅황금 아이템의 등장 확률

**Comment by pdom0327** [comment]
[golden-items.zip](https://github.com/user-attachments/files/17137537/golden-items.zip)
원본 모드대로 그대로 옮겼습니다. 복시, 리롤 처리도 기존 모드 따라갑니다.

황금 액티브 아이템 획득 시 UI에 황금 효과가 보이지 않아서 등장하지 않도록 해두었습니다만,
황금 아이템 상태에서 리롤 시 등장할 수 있습니다.
