### ISSUE TITLE
럭키 동전 리젠 속도, 엔티티 배속 유무, 역탄 석탄 컨셉 신규 아이템 구현 유무

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#428]
Q1 : 럭키 동전을 획득 후 리젠되는 시간을 조정하고 싶습니다. 이번에 자폭 파리, 거미처럼 럭키 페니 자체 동전에 배수를 걸어서 순식간에 먹는 플레이가 가능할까요?

Q2 : 1번이랑 비슷한 질문인데, 엔티티만 존재하는 모든 요소에 배수를 걸 수 있을까요? 현재 대결모드에서는 악마거지 로컬파일에 존재하는 수치를 건드려서 배속이 걸려 있습니다. 가능하다면 거지류 및 배속이 필요한 엔티티 요소에 전부 적용하고 싶습니다

Q3 : 특정키를 조작하여 원하는 패시브 아이템을 지웠다가 넣는 방식이 가능할까요? 아래 아이템을 제작하려 합니다

패시브 아이템 : 흑탄(역탄+석탄 컨셉템)
1. 획득시 석탄 적용 상태가 됩니다
2. 할당 키 누를 시, 역탄이 적용됩니다 (역탄 적용 시, 석탄은 상관 없음 어차피 역탄 패널티에 다 묻힘)
3. 다시 할당키를 누를 시 역탄 효과 x

일단 히든아이템 모드를 사용하여 온 / 오프를 생각중입니다. 더 좋은 방법이 있거나 다른 방법이 있다면 이야기 해주세요

그리고 위에 방법이 어렵다면 2안도 가능한지 알고 싶습니다
1. 방 클리어 시 역탄, 석탄 번갈아가면서 적용

**Comment by pdom0327** [comment]
A1. 가능합니다.
https://github.com/user-attachments/assets/3d2a0eed-7bc6-4886-9e29-d8a5b552c759

A2. 어떤 버그가 있을지는 모르겠는데 가능하긴합니다.

A3. 가능합니다.
