### ISSUE TITLE
feat: 닥터 페투스 소지 시 로켓이 들어오지 않는 현상

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#431]
예전에 닥터페투스와 에이플을 소지한 상태에서 보스 클리어 시, 로켓폭탄이 없을경우 캐릭터에게 로켓폭탄을 지급하는 효과가 있었는데 현재 적용되지 않습니다

정확하지는 않지만 모드를 분리하면서 사라진거 같습니다

**Comment by pdom0327** [comment]
#38 에서 Host Hat 소지 시 지급 되지 않는 코드가 있었습니다. 제거하겠습니다.
