### ISSUE TITLE
대회 컨텐츠에서 시청자들이 사용할 최적화 모드

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#432]
✅특정 단축키를 사용해서 게임을 바로 리셋 할 수 있는 버튼 (기본 할당키 U)
✅레드방을 포함한 모든 스테이지 구조 확인 가능
✅XL 저주를 제외한 모든 저주 면역 (저주 면역 모드 있는거 알지만 변인통제 깔끔하게 하기 위함)

**Comment by pdom0327** [comment]
[hy-challenge.zip](https://github.com/user-attachments/files/17113302/hy-challenge.zip)
