### ISSUE TITLE
newmod: 골든 페니에 배속을 걸 수 있는 모드

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#433]
✅최근 제작한 파리 배속 모드와 동일하며, 대상을 골든 페니로 취급해서 제작합니다

모드 이름 : 대충 패스트 럭키 페니

**Comment by pdom0327** [comment]
[fast-golden-penny.zip](https://github.com/user-attachments/files/17140915/fast-golden-penny.zip)
