### ISSUE TITLE
bug: 황금아이템 버?그

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#434]
![image](https://github.com/user-attachments/assets/4ea61db6-a5dc-47dc-a804-2155bf203a7f)

게임 시작 시 위 오류가 발생
모드 자체 구동에는 문제는 발생하지 않음

몇번째줄보이길래 일단 깃에 적어놓습니다

**Comment by pdom0327** [comment]
[golden-items-240928.zip](https://github.com/user-attachments/files/17166761/golden-items-240928.zip)
#435 와 함께 해결했습니다.

- **기존 파일로 작업했으므로 확률 재설정 해주셔야 합니다.**
- **창작마당 꼬일 수 있으니 metadata.xml는 기존 파일 사용해주세요.**

**Comment by iwt2hw** [comment]
역시 대단해 안프돔
