### ISSUE TITLE
bug: 은하용맹 훈장 중첩 관련

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#436]
![image](https://github.com/user-attachments/assets/ce2a24c9-be75-4f74-9691-201b997fce2f)

![image](https://github.com/user-attachments/assets/793e0e68-e749-42d5-8057-33cfcc2a7b20)

곱연산 합연산 둘째치고 먹을수록 효율이 떨어지는 버그가 존재합니다

**Comment by pdom0327** [comment]
#351 확인 된 오류입니다. 고쳐야 할 아이템이 많아서 우선 순위 미루고 있었는데 빠르게 수정하겠습니다.
