### ISSUE TITLE
fast fly 밸런스를 위한 설정 관련

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#438]
대결 모드에서는 파리 속도가 2배여도 상관 없지만

순정에서는 파리를 소환하는 로튼베이비 실질 성능이 올라가버리는 문제가 발생 됩니다

상황에 맞게 능동적인 밸런스를 위해 아래 기능을 추가합니다

속도의 경우에도 맨 2배속도 충분히 빨랐음

✅파리 + 거미가 설정한 수치 이상이 되었을경우 실시간으로 2배속으로 변경됩니다
✅해당 옵션이 추가됨에 따라 게임 시작 시 초기화되는 옵션은 불필요함으로 제거합니다
✅불가능할거같진않은데, 파리 + 거미 합산 체크가 어려울경우 자폭 파리만을 체크해도 상관 없습니다
[fast-fly.zip](https://github.com/user-attachments/files/17290531/fast-fly.zip)

**Comment by pdom0327** [comment]
[fast-fly-241011.zip](https://github.com/user-attachments/files/17342433/fast-fly-241011.zip)
