### ISSUE TITLE
newitems: Dracoback, the Rideable Dragon(기룡 드라코백)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#439]
용사 테마의 아이템입니다
해당 아이템은 실제 유희왕에서 상대 카드를 견제(없애)버리는 컨셉이라 그에 맞게 지우개로 짜려합니다
아래 지우개 관련 플레이중 가능한것들부터 답변 부탁드립니다

❗아이템 효과❗
✅방 입장 시 랜덤한 일반 몬스터 한마리가 지우개 효과로 제거됩니다
└중복 개수일 경우 제거되는 몬스터의 개수 증가
✅가장 처음으로 죽은 몬스터 한마리가 지우개 효과로 제거됩니다
└중복 개수일경우 발동 두번째, 세번째 발동 횟수가 증가됩니다

❗중복 효과❗
✅상기 기재 내용 확인

❗추후 직접 조절할 수도 있는 요소 (최대한 반복 작업 방지용)
✅없음

❗모드 컨피그로 조절할 수 있으면 하는 사항 (아래 요소들인 딸1깍으로 수정 가능하게 짜면 별도로 다시 밸런스 패치 요구할 확률이 많이 줄어듦)

**Comment by pdom0327** [comment]
둘다 가능합니다

**Comment by iwt2hw** [comment]
용사 테마답게 캐릭터가 수견사나 일릭걸 나이트일경우 효과가 강화됩니다

1. 지우개 효과로 제거되는 몬스터의 개수 +1

예시) 드라코백2개 + 캐릭터가 수견사 = 3회 발동

또한 해골바가지 및 보스방에서 지우개가 발동되는 현상을 방지하기 위해 보스방에서는 발동되지 않도록 예외처리 합니다
