### ISSUE TITLE
feat: 신규 세트 효과 테스트

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#440]
![image](https://github.com/user-attachments/assets/959c5e59-aafc-4367-ac85-cfe79645a6d5)

https://github.com/user-attachments/assets/7bb9ca5b-4b14-40de-b8ad-11e8464d1c2e

[헤블론의군주,포프루스 anm.zip](https://github.com/user-attachments/files/17291183/anm.zip)

첨부된 anm 파일이 아이작에서 두번쨰 사진처럼 작동되는지 확인 부탁드립니다

**Comment by pdom0327** [comment]
![image](https://github.com/user-attachments/assets/30ced0cb-5159-43a9-82c2-dc8c10b8a364)

**Comment by iwt2hw** [comment]
확인 완료
