### ISSUE TITLE
newitems: 놀라운 긍정의 혼돈 주문서

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#442]
기존 혼돈의 주문서와 완전히 동일하며, 긍정이라서 감소되지 않는 컨셉의 아이템입니다
영어 명칭은 메이플위키에가서 직접 부탁드립니다..

✅기존 놀혼줌에서 수치만 바뀌는거라 복붙 하셔도 됩니다
✅수치는 직접 조절 하겠습니다

**Comment by pdom0327** [comment]
영문명은 Incredible Chaos Scroll of Goodness 이지만 기존 놀혼줌에 맞춰서 Amazing Chaos Scroll of Goodness 으로 하겠습니다.
