### ISSUE TITLE
feat: 대결 모드 마더루트 실수 완화 패치#2

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#447]
기존 폴라없이 지옥, 네거티브 없이 성당 실수 방지를 위한 플레이 입니다
마더루트에서 루트 실수로 인한 진빠지는 상황 방지가 목적입니다
보스 루트가 마더일 경우에도 고의적으로 일반 진행 악용 방지를 위하게 설계되었습니다

✅신규 엔티티 마더 포탈을 추가합니다
✅해당 포탈은 1챕터 보스,상점,황방 포탈과 유사합니다
✅실수로 인한 포탈 입장 방지를 위해, 아래 사진 빨간 박스에 포탈을 배치합니다 (깃 다운로드하면 최신 버전은 저 공간 비워져 있음)
![image](https://github.com/user-attachments/assets/8608661c-cd5d-463a-b3d5-de6cee162c0a)

**Comment by pdom0327** [comment]
마더 스테이지 시작방으로 이동하나요? 아니면 보스방으로 이동하나요?

**Comment by iwt2hw** [comment]
6스테이지(히든, 게헤나) 이동됩니다

**Comment by iwt2hw** [comment]
![image](https://github.com/user-attachments/assets/551b53d5-d567-49c4-afc6-59ee128753ff)

![image](https://github.com/user-attachments/assets/47171f6e-263a-444f-8ebc-8f83e71ea57a)


의도된 위치는 8스테이지 보스 처치 후, 허쉬 들어가기전 방입니다
