### ISSUE TITLE
feat：시작방 이지모드, 베리이지모드 일정 시간이 지나면 제거

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#451]
✅1안으로 진행합니다
✅시간은 10초라 하되, 언제든지 수정할 수 있게 별도 주석 부탁 드립니다
✅추후 이지모드 아이템은 솔로플레이 및 배열로 설정할 예정입니다 (일정 시간 지나면 모든방에 이지모드 제거<-- 이런식으로 짜지 말라는 뜻. 황금방에서 나오자마자 지워지는 등의 버그 현상 케어)

------------------------------------------------------------------

게임 시작직후 시작방 돌아다니면서도 계속 남아있는 현상을 완화합니다
아래 2개의 안건 둘 다 가능한가요?

❗아이템 효과 및 기능❗
1안) 게임 시작직후 설정한 시간이 지났을 경우 시작방에 이지모드, 베리이지모드 제거
2안) 게임 시작직후 캐릭터가 방을 이동했을경우 시작방에 이지모드, 베리이지모드 제거

**Comment by pdom0327** [comment]
둘다 가능합니다.

**Comment by iwt2hw** [comment]
본문 내용 수정 했습니다

**Comment by pdom0327** [comment]
시작 방에서는 10초가 지나면 콘솔로 소환한 이지모드도 강제 삭제 됩니다.
