### ISSUE TITLE
newitems：Abortion(낙태)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#454]
![image](https://github.com/user-attachments/assets/e3b85732-c829-4136-b2ef-5257cf882ba3)

❗효과 및 기능❗
✅눈물이 몬스터에게 명중될 경우 제왕절개로 변경되는 낙태 눈물을 발사합니다
✅낙태 눈물은 뱀눈 아이템과 마찬가지로 소환쿨타임(발동쿨타임도 상관X) + 기본 확률 + 행운당 수치%p 증가 설정합니다

❗중복 효과❗
✅소환 쿨타임 감소 (뱀눈과 동일하게 코딩 하면 됩니다)
✅기본 확률 증가 (합연산, 곱연산 그 외 방식 다 상관없으며, 주석 처리로 방식만 기재 해주세요)
✅행운당 수치%p 추가 증가 (합연산, 곱연산 그 외 방식 다 상관없으며, 주석 처리로 방식만 기재 해주세요)

[낙태.zip](https://github.com/user-attachments/files/17484428/default.zip)

**Comment by pdom0327** [comment]
가능할 듯 합니다

**Comment by iwt2hw** [comment]
본문 내용 수정 했습니다

**Comment by pdom0327** [comment]
> ✅행운당 수치%p 추가 증가 (합연산, 곱연산 그 외 방식 다 상관없으며, 주석 처리로 방식만 기재 해주세요)

행운 당 수치가 중첩되는 아이템은 없었어서 의도하신 바가 맞는지 확실하진 않으나 일단 추가했습니다.

+ 낙태 눈물 이미지가 있으면 좋을 거 같습니다.
