### ISSUE TITLE
newitems：RGB(삼원색)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#456]
❗효과 및 기능❗
✅획득 시 sfx 소리가 출력됩니다 (작동만 확인되면 직접 파일 수정 하겠습니다)
✅방 입장 시 빨간색, 녹색, 파란색으로 색상이 변경됩니다 (아이템 기억은 안나지만 와카바모드의 방 색상을 바꾸는 아이템이 존재합니다)
✅색상에 따라 추가 효과가 발동됩니다
└빨간색 : 공격력 배수 증가
└녹색 : 럭 배수 증가
└파란색 : 연사 배수 증가

❗중복 효과❗
✅빨간색 : 배수 추가 증가 (합연산, 곱연산 뭐든지 상관 없고, 방식만 주석 처리)
✅녹색 : 배수 추가 증가 (합연산, 곱연산 뭐든지 상관 없고, 방식만 주석 처리)
✅파란색 : 배수 추가 증가 (합연산, 곱연산 뭐든지 상관 없고, 방식만 주석 처리)

❗추후 루아 내에서 직접적으로 간단하게 조절할 수 있는 요소
✅색상별 증가하는 배수의 수치

**Comment by kohashiwakaba** [comment]
되도록(특히 모래시계가 중요한 경우) #66 선적용이 필요합니다.
