### ISSUE TITLE
feat：Quantum Mind(퀀텀마인드)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#459]
✅캐릭터 스피드가 2.0 이상일경우 스피드 마인드가 등장하지 않도록 변경합니다

**Comment by pdom0327** [comment]
2.0 이상일 경우 배열에서 제거해버려도 되나요?

**Comment by iwt2hw** [comment]
확인했습니다

**Comment by pdom0327** [comment]
이속이 2.0 이상이면 Swift Mind가 자연 등장하지 않는 걸로 착각했었습니다. 퀀텀 마인드에서 미등장으로 수정했습니다.
