### ISSUE TITLE
스파이더모드의 기능만 사용 가능할까요?

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#460]
https://steamcommunity.com/sharedfiles/filedetails/?id=1640766291&searchtext=

![image](https://github.com/user-attachments/assets/dcedff3d-a6e9-4680-af32-de864e663e60)

현재는 1번키를 눌러 데미지 표시를 온 / 오프 핫키 사용중인데 폰트가 ㅈ구려서 스파이더모드로 바꾸고 싶습니다
게임 영향이 가지 않고 스파이더모드 소지 시 폰트만 적용 가능할까요?

위 내용이 안된다면 디버그 데미지 표시 폰트 변경이 가능한지와 투명도 적용이 가능한지가 궁금합니다

**Comment by iwt2hw** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2918355263&searchtext=

**Comment by pdom0327** [comment]
> https://steamcommunity.com/sharedfiles/filedetails/?id=2336582959&searchtext=
이 모드에 온오프 키 추가하면 되는걸까요?

**Comment by iwt2hw** [comment]
두가지 모드 다 써본결과 이 모드에 온오프 기능만 추가해주시면 됩니다
할당키는 직접 수정해서 쓰겠습니다

https://steamcommunity.com/sharedfiles/filedetails/?id=2918355263&searchtext=

(아래 모드는 조잡하고 기능만 많지, 위 모드가 딱 심플함)

**Comment by pdom0327** [comment]
[spidermod+-20241028.zip](https://github.com/user-attachments/files/17534859/spidermod%2B-20241028.zip)
