### ISSUE TITLE
악마방 천사방 현재 확률 관련

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#461]
보스방을 처치 하기전 현재 악마 / 천사방이, 이번 스테이지 악마방 천사방을 열리는지에 유무를 알 수 있을까요?

구피눈, 모시눈처럼 악마 컨셉인 염소 눈깔 아이템을 기획하려 합니다

효과 : 현재 악마 / 천사 확률이 보스방 클리어 후 열리는지를 알려줍니다

**Comment by pdom0327** [comment]
level:GetDevilAngelRoomRNG()로 뭔가 해볼 수 있지 않을까 싶었는데 당장은 방법이 없습니다.
