### ISSUE TITLE
feat：삼손

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#466]
론고미니아드가 실전에서 과도한 파워가 예상됩니다
✅론고미니아드도 아라메시아의 의와 동일하게 스테이지 입장 시 쿨타임 전부 회복
✅수견사 일리걸과 동일하게 쿨타임을 100칸으로 설정해서 밸런스할 계획

**Comment by pdom0327** [comment]
쿨타임 50으로 설정했습니다
