### ISSUE TITLE
테크오미크론과 혼줌, 놀긍혼 연산문제

### ISSUE THREAD

**Issue by makabeP** [TeamHY/Astrobirth#467]
![image](https://github.com/user-attachments/assets/db61aa92-661f-4ad0-8c9d-7767a489203f)

혼줌1.2배 오미크론10개면 연사가 0.45여야하는데 1.62로 적용됩니다
오미크론 0.8배에 혼줌1.2배면 연사가 0.96이여야하는데 0.8+0.2 이렇게 적용됩니다
오미크론이 2개면 0.64+0.2로 적용되고

**Comment by pdom0327** [comment]
우선 순위 통일하였습니다.
