### ISSUE TITLE
게임 자체 진행 불가 오류 2개

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#468]
![image](https://github.com/user-attachments/assets/03d0b034-2bb9-4ed8-8aa2-c31a71e20953)

금고방 입장 시 팅김 (루아 먹통)

![image](https://github.com/user-attachments/assets/564c44a3-0336-4075-b9d4-a7f6feffd9d3)

숏컷 포탈 작동 안됨

**Comment by pdom0327** [comment]
<img width="884" alt="image" src="https://github.com/user-attachments/assets/29954abf-a107-4551-9fcb-e6f783a0b64f">

숏컷 포탈은 수정했습니다.

금고방은 동일 시드로 테스트 해봤는데 위 문제를 수정해서인지 오류를 못 찾았습니다.
