### ISSUE TITLE
신규 업데이트 : 카드

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#47]
【카드】
I - The Cold
└현재 방에서 둔화가 적용됩니다 (모래시계 3회 효과와 동일)
II - The Servant
└이번 스테이지에서 랜덤한 보조딜러 한마리가 소환됩니다 (몬스터 메뉴얼 1회 효과와 동일)
III - Wisdom
└일급 비밀방으로 이동됩니다
IV - Repentance
└해당 방 안에 수집아이템을 리롤시킵니다 (6각 주사위 1회 효과와 동일)
V - Eternity
└사용 시 이터널 하트가 1~4개까지 소환됩니다
VI - Corruption
└사용 시 에러방으로 이동됩니다
VII - Immolation
└사용 시 희생방으로 이동되며, 현재방에 희생방이 없을 경우 랜덤한 위치로 이동됩니다
VIII - Worship
└사용 시 50% 확률로 해당 방 안에 아이템이 소환됩니다 (콘솔 spawn 5.100 적용)
└아이템 소환에 실패 시 캐릭터에게 배드 트립 알약을 1회 적용시킵니다

[앞면.zip](https://github.com/TeamHY/Astrobirth/files/13463360/default.zip)
[뒷면.zip](https://github.com/TeamHY/Astrobirth/files/13463359/default.zip)

**Comment by pdom0327** [comment]
앞면 이미지는 어떤걸로 하면 될까요?

**Comment by iwt2hw** [comment]
1 하얀색 카드는 다른 특수용 카드임 상기 기재된 추가 카드들은 앞,뒤 전부다 검정색
2 예-스 어차피 알아서 중첩됨
