### ISSUE TITLE
스파이더모드 단축키 관련

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#470]
https://github.com/TeamHY/Astrobirth/issues/460

체력바 기능이 생각 거슬리거나 필요가 없습니다

![image](https://github.com/user-attachments/assets/9d827280-68db-4d2d-91c3-8a711db1d12c)

✅파란색 부분은 어차피 항시 on 이라 건드릴 필요 없습니다 (현재도 방식도 건드리지 않는 세팅이지만 혹시나 헷갈릴까봐 한번더 이야기 하는거임)
✅데미지넘버랑 헬스바를 【각각】 단축키로 조절할 수 있는걸 원합니다 (현재는 키 하나로 온 / 오프 변환식임)
└예시) 1번키를 눌러 데미지만 온 / 오프 조절
└예시) 2번키를 눌러 체력바만 온 / 오프 조절
✅작동 확인만 체크해주시면 키는 직접 변경해서 사용 하겠습니다

**Comment by pdom0327** [comment]
[Uploading spidermod+-20241104.zip…]()
