### ISSUE TITLE
feat：Dracoback, the Rideable Dragon(기룡 드라코백)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#472]
예상보다 과도한 성능을 조절합니다

1안) 스테이지 입장 시에 초기화 되며, n회에 방까지만 발동하도록 변경
2안) 제한은 없으나 행운 수치를 받도록 변경

어떤것들이 가능할까요?

**Comment by pdom0327** [comment]
둘 다 가능합니다.

**Comment by iwt2hw** [comment]
1번으로 진행합니다

1. 캐릭터가 용사일경우 5회 발동
2. 캐릭터가 용사 이외일 경우 2회 발동

각각 발동 횟수는 변경될 수 있으므로 코딩 시 참고
