### ISSUE TITLE
모드 리뷰 컨텐츠를 위한 모드

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#475]
특정 모드에 아이템 리뷰 컨텐츠를 할 때, 해당 아이템만을 사용해서 순정에서 사용 하고 싶습니다

예) 아스트로 모드를 깔았지만 아이템, 장신구는 순정만 사용하고 싶고, 원하는 아이템이나 실험은 콘솔로 꺼내서 사용하는게 목적

![image](https://github.com/user-attachments/assets/f1e23780-19e9-4c39-9cab-5c47fd5d17d8)
![image](https://github.com/user-attachments/assets/b659e76e-9be5-4e95-b729-5d197e09fb42)

✅모드를 적용한 상태더라도 순정 아이템들만 나오도록 합니다
✅아이템의 경우 끝번호가 732, 장신구 189번인데, 대결 모드의 펄린오브처럼 "아이템 등장 시, 해당 번호를 초과할경우 리롤" 방식으로 생각중입니다 (더 좋은 방법있으면 그걸로 채택해도됨)
✅모드컨피그 모드로 실시간 온 / 오프를 지원합니다 (온하면 리롤이라 순정만 등장, 오프면 모드 아이템 전부 등장)
✅아이템만 따로, 장신구만 따로 온 / 오프 기능은 없어도 됩니다 (지울꺼면 전부 한번에 같이 지워진다는뜻)

**Comment by pdom0327** [comment]
[review-helper.zip](https://github.com/user-attachments/files/17840007/review-helper.zip)
