### ISSUE TITLE
feat：fire mind, bbf(폭발파리)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#478]
생과일, 에픽, 구토제, 닥터와 동일하게 소지 시 호스트햇을 적용합니다 (다른 면역 아이템들과 해당 아이템이 사라지면 폭발 면역도 사라집니다)

**Comment by pdom0327** [comment]
파이어 마인드는 이미 적용되어있습니다.
해당 목록은 아스트로버스 `astro-fight/collectibles/vanillas/host-hat.lua`에서 수정하실 수 있습니다.
