### ISSUE TITLE
라헬 시작 아이템 "순애" 리뉴얼

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#484]
대결모드가 없을경우 밴 시스템이 존재하지않아 아이템이 깡통화됩니다
또한 밴을 제거시키는 리인카네이션과 과도한 역시너지로 인해 완전 리뉴얼합니다

✅일급 비밀방에서만 사용 가능
✅방을 나갈경우 소환한 아이템 제거
✅사용 시, 소지한 아이템 1개 + 3 or 4 퀄리티 아이템 등장 (둘 중에 하나만 먹을 수 있음)
✅레아,라헬,야곱,알트야곱 이외에 사용 시, 행운 -1 감소
✅해당 아이템을 소지하고 있는 상태이고, 스테이지 1일경우 일급 비밀방 위치 미니맵에 표시

**Comment by pdom0327** [comment]
소지 했던 아이템은 제거 하나요?

**Comment by iwt2hw** [comment]
네 제거 됩니다 (기존템 유지 or 3~4퀄 먹을지가 의도된 컨셉)
