### ISSUE TITLE
feat：Pisces EX

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#489]
역 매지션 카드가 발동할 때 마다 사운드가 출력됩니다
사운드 파일 이름은 Pisces EX.wav 설정 해주시고, 소리 출력 유무만 테스트 해주세요
직접 파일 바꿔서 사용 하겠습니다

**Comment by pdom0327** [comment]
resources/sfx/feedback/pisces-ex.wav 파일 수정하시면 됩니다.
