### ISSUE TITLE
커스텀아이템들 중첩 변경 유무

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#57]
해당 아이템들을 여러개 획득 시 중첩가능하도록 변경
※확률형 합연산 + 곱연산 상관없으나 중첩 적용 시 템 설명에 기재

![Angry Onion](https://github.com/TeamHY/Astrobirth/assets/28684443/412c7566-7094-4965-a027-61e785a56ab0)
![Aquarius](https://github.com/TeamHY/Astrobirth/assets/28684443/b1ca1ae1-3de6-442e-afec-e128d135c6b7)
![Bomb Is Power](https://github.com/TeamHY/Astrobirth/assets/28684443/f4a2202f-334c-47f8-aa49-54860df0bcca)
![Cancer](https://github.com/TeamHY/Astrobirth/assets/28684443/56d75853-9878-41d7-bb32-113aea682e73)
![Casiopea](https://github.com/TeamHY/Astrobirth/assets/28684443/ff3fbe63-84c3-4741-b32c-3e45698e79ac)
![Chubby's Head](https://github.com/TeamHY/Astrobirth/assets/28684443/55a56ca3-d20e-45c4-b773-44810b30d326)
![Chubby's Tail](https://github.com/TeamHY/Astrobirth/assets/28684443/8c5ede45-85e9-4320-92c2-ff43a687e044)
![Clover](https://github.com/TeamHY/Astrobirth/assets/28684443/71ddb147-9835-490c-b8fc-25880cec0f72)
![Comet](https://github.com/TeamHY/Astrobirth/assets/28684443/92107729-f82c-466d-bdb7-d1c928afa31a)
![Corvus](https://github.com/TeamHY/Astrobirth/assets/28684443/8ed7afdd-78d2-42bb-8ea8-226af9b1067c)
![Cursed Heart](https://github.com/TeamHY/Astrobirth/assets/28684443/57e306d3-b578-4a72-a347-e36a2b9b2820)
![Cygnus](https://github.com/TeamHY/Astrobirth/assets/28684443/6032350f-6bb6-45af-b136-cd223ca5301e)
![Death's Eyes](https://github.com/TeamHY/Astrobirth/assets/28684443/4f3e8675-b9ff-4806-b631-e01d840ee3a5)
![Divine Light](https://github.com/TeamHY/Astrobirth/assets/28684443/502b21d0-fffe-406b-af0f-28e8aef70a85)
![Galactic Medal Of Valor](https://github.com/TeamHY/Astrobirth/assets/28684443/81c3a3e2-24fb-4f2a-8808-9cd43e011a0f)
![Happy Onion](https://github.com/TeamHY/Astrobirth/assets/28684443/58f30332-ecbb-436a-9961-b38d63c4f240)
![Key Is Power](https://github.com/TeamHY/Astrobirth/assets/28684443/a1e32021-db6b-4504-b4ba-e09bd8bbb18b)
![Omega 321](https://github.com/TeamHY/Astrobirth/assets/28684443/9a2b268f-c11a-4bb9-8022-c663eb61f7a4)
![Pavo](https://github.com/TeamHY/Astrobirth/assets/28684443/eb38b8e5-b4b2-46f6-9bfb-502dd0d16d27)
![Pirate Map](https://github.com/TeamHY/Astrobirth/assets/28684443/bbf4d10a-6e1a-4289-bf86-e5f94e783a82)
![Pisces](https://github.com/TeamHY/Astrobirth/assets/28684443/46823443-9c66-4d58-bf78-e6c53f301808)
![Platinum Bullet](https://github.com/TeamHY/Astrobirth/assets/28684443/7d865a19-8c52-4bf9-b23f-81b8f03fa6fd)
![Prometheus](https://github.com/TeamHY/Astrobirth/assets/28684443/c69e917a-2a43-4bca-a188-ef745b347ee4)
![Quasar](https://github.com/TeamHY/Astrobirth/assets/28684443/01d201da-bde3-4ba0-be8d-1584fa2d69d0)
![Sagittarius EX](https://github.com/TeamHY/Astrobirth/assets/28684443/f376526b-9e74-4c41-a457-8ca77abe24bf)
![Sleeping Puppy](https://github.com/TeamHY/Astrobirth/assets/28684443/542a9537-d2e1-41b0-b29f-c460d61bb72d)
![Taurus](https://github.com/TeamHY/Astrobirth/assets/28684443/a5954bbd-6816-4caf-8f01-cc9cc3ceb8d8)
![Acute Sinusitis](https://github.com/TeamHY/Astrobirth/assets/28684443/88bd3341-cab9-456a-a2d1-fa6b3b834d3f)

**Comment by pdom0327** [comment]
- aquarius-ex: 
  - 7 프레임마다 눈물 생성에서 중첩 효과를 어떻게 적용하면 좋을지 모르겠습니다. (7 / 소지 개수) 프레임마다 발동하도록 할까요?
  - 일반 물병자리의 중첩 효과는 어떻게 처리해야할까요?
    - ex1) 일반 물병자리 x2
    - ex2) 일반 물병자리 x2, 극 물병자리 x1
- 획득 시 효과: 알트 아이작 들었다 놨다, 컨티뉴 시 재발동 등을 막기 위해 모든 획득 시 효과는 게임 당 한 번만 발동하도록 되어있습니다. 이번 이슈에서 당장 변경하기는 어렵습니다.
- (추가 사항 있으면 업데이트 하겠습니다)

**Comment by iwt2hw** [comment]
1. 물병자리의 경우 그냥 중복 처리 하지 않아도 됨
2. 1번과 마찬가지로 이 경우 코드 다 뜯어야하는데 당연 안해도 됨

**Comment by iwt2hw** [comment]
Q : 7 프레임마다 눈물 생성에서 중첩 효과를 어떻게 적용하면 좋을지 모르겠습니다. (7 / 소지 개수) 프레임마다 발동하도록 할까요?
A : 물병자리와 극 물병자리는 그냥 중복 적용x

일반 물병자리의 중첩 효과는 어떻게 처리해야할까요?
ex1) 일반 물병자리 x2
ex2) 일반 물병자리 x2, 극 물병자리 x1
A : 물병자리와 극 물병자리는 그냥 중복 적용x

Q : 획득 시 효과: 알트 아이작 들었다 놨다, 컨티뉴 시 재발동 등을 막기 위해 모든 획득 시 효과는 게임 당 한 번만 발동하도록 되어있습니다. 이번 이슈에서 당장 변경하기는 어렵습니다.
A : 마찬가지로 컨티뉴 및 재발동 방지가 되어있는 아이템은 중복 적용에서 예외 처리


---------------------------------
-버그 관련
1.카시오페아가 작동되지 않음 (중첩을 떠나서 그냥 먹통)
2.폭탄이즈파워가 중첩은 정상적으로 되나 캐시 갱신 시 적용됨 (예:컨티뉴 및 다른 스텟 변화가 있을 시)
3. 케인눈깔 버그 관련 (카톡에 스크린샷 루아 올려놨음)
