### ISSUE TITLE
(23.12.22 추가) 업데이트: 다모클래스 #2

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#63]
1.피격 시 가장 최근에 먹은 아이템 + 가장 마지막에 획득한 아이템 제거
예시)
첫번째 아이템 엄마식칼
두번째 아이템 싸클
세번째 아이템 불심
상태에서 피격을 당했더라면 엄마식칼과 불심 제거

2. 다모클래스 사용 시 체력 제한 시스템이 적용되도록 변경

3. 다모클래스(패시브) 소지 시 홀리 카드 즉시 제거 (기존 유다 코드에서 조건만 변경)

**Comment by pdom0327** [comment]
게임 재실행 시, D4 사용 시 피격 제거되는 아이템 순서가 번호 오름차순으로 바뀝니다. 전자는 세이브 기능 수정하면서 고칠 예정이고 후자는 방법이 없네요.

**Comment by iwt2hw** [comment]
23.12.22 추가)
4. 위에 1번 항목 전부 철회하고, 가장 최근에 먹은 아이템 4개가 지워지도록 변경 (이게 가독성 보기 좋음)
