### ISSUE TITLE
❗❗❗우선순위급함) 퀵 옵션 모드에 아래 기능들 추가

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#73]
[Q_Option.zip](https://github.com/TeamHY/Astrobirth/files/13767713/Q_Option.zip)

1. 몬스터에게 어느정도의 피해를 입힌 지 확인 가능한 기능 (콘솔 -> debug 7) 루아로 키 할당 후 원 클릭으로 온 / 오프 할 수 있도록 변경
2. 게임 시작 시 콘솔 -> 디버그 7 기능을 ON으로 초기화
3. 게임 시작 시 오른쪽 아이템 허드 크기를 스몰 단계로 초기화
4. 캐릭터가 클리어 되지 않은 보스방에 입장 시, 오른쪽 아이템 허드 크기를 없앰으로 변경 (시야 확보)
5. 보스방 클리어 시 오른쪽 아이템 허드 크기를 다시 스몰 단계로 초기화

**Comment by pdom0327** [comment]
[Q_Option.zip](https://github.com/TeamHY/Astrobirth/files/13773506/Q_Option.zip)
