### ISSUE TITLE
신규 캐릭터 레아

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#74]
[leah (2).zip](https://github.com/TeamHY/Astrobirth/files/13767906/leah.2.zip)

별도의 효과는 없어도 되니 첨부된 파일 사용해서 추가만

**Comment by pdom0327** [comment]
![character_leah](https://github.com/TeamHY/Astrobirth/assets/12953393/c97bc734-13d5-41c0-a7c0-6a05bbaba738)

위쪽 머리에도 머리카락이 필요합니다.

**Comment by iwt2hw** [comment]
민이한테 전달 완료
