### ISSUE TITLE
수정#2) 보스 룰렛 모드

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#75]
[bossroulette_v2_3043157956.zip](https://github.com/TeamHY/Astrobirth/files/13775685/bossroulette_v2_3043157956.zip)
![KakaoTalk_20231230_135034351](https://github.com/TeamHY/Astrobirth/assets/28684443/17b4c148-0243-43b2-b340-7295808b8714)

자주색으로 변경

**Comment by pdom0327** [comment]
![image](https://github.com/TeamHY/Astrobirth/assets/12953393/74445f6e-e66e-4d3f-b7c2-b5e4b73000ff)


>  -컨티뉴 시작 시 설정된 보스방이 초기화되는 문제 해결 (초기화는 게임 재시작시에만..)

저는 컨티뉴랑 게임 껏다 키고 컨티뉴 둘 다 정상 작동해서 어떤 문제인지 모르겠습니다.

[bossroulette_v2.zip](https://github.com/TeamHY/Astrobirth/files/13795602/bossroulette_v2.zip)

**Comment by pdom0327** [comment]
[bossroulette_v2.zip](https://github.com/TeamHY/Astrobirth/files/13797737/bossroulette_v2.zip)

텍스트 컬러로 수정했습니다.

**Comment by iwt2hw** [comment]
문제 없음 굳
