### ISSUE TITLE
챌린지 추가 업적 관련

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#78]
-로스트로 마더 클리어 (Cygnus)
-로스트로 메가사탄 클리어 (Libra EX)
-로스트로 체스트 클리어 (Cancer EX)
-로스트로 다크룸 클리어 (Scorpio EX)

-챌린지 이름은 해금 아이템 명칭과 동일

**Comment by pdom0327** [comment]
대결 상대가 언락하지 않은 상태면 어떻게 하나요?

**Comment by iwt2hw** [comment]
상관없음

해금안하면지만손해니

즉 대결은 고려사항이 아님

해금되어있으면되어있는대로 ㅇㅇ
