### ISSUE TITLE
LUA) 밴 관련 최적화

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#79]
-카드 알약 룬을 ban 에서도 설정할 수 있도록 변경
-아이템, 장신구처럼 루아사이트에서 복붙만으로 작업 가능할 수 있도록 ㅇㅇ
-해당 깃이슈에 루아 카드, 알약,룬 사이트 기재해놓기

**Comment by pdom0327** [comment]
[카드](https://wofsauge.github.io/IsaacDocs/rep/enums/Card.html)
[알약](https://wofsauge.github.io/IsaacDocs/rep/enums/PillEffect.html)

알약 밴 로직이 변경되었습니다.
- 금지된 알약을 걸프로 변경 -> 금지된 알약이 나올 경우 삭제하고 재생성 (다른 알약이 나올 확률이 증가합니다)
