### ISSUE TITLE
퀵옵션 모드 관련

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#80]
-현재 디버그7 OFF 상태에서 컨티뉴를 하면 다시 디버그 7 On 상태로 변경됨
-컨티뉴시 디버그 7 상태가 변경되지 않도록 수정
[Q_Option.zip](https://github.com/TeamHY/Astrobirth/files/13800830/Q_Option.zip)

**Comment by pdom0327** [comment]
[Q_Option.zip](https://github.com/TeamHY/Astrobirth/files/13814465/Q_Option.zip)

**Comment by iwt2hw** [comment]
테스트 문제 없음
