### ISSUE TITLE
상황에 맞는 BGM 재생

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#81]
-1 ~ 6 스테이지 까지 브금
└캐릭터가 1 ~ 6 상태일경우 출력

-1스테이지 히든(물, 하수구) 스테이지에서만 전용 브금
└캐릭터가 1챕터(1,2 히든 스테이지) 상태라면 출력

-7 스테이지 이후 브금
└스테이지가 7스테이지 이상이라면 출력

-보스방 전용 브금
└캐릭터가 현재 보스방에 있고, 보스방이 미 클리어 상태라면 출력

-파이널 보스 전용 브금 (데릴리움, 메가사탄, 도그마, 비스트, 마더, 울트라 그리디어)
└캐릭터가 항기방에 존재하고, 현재 보스방이 미클리어 상태라면 출력

-파이널 보스 클리어 시 브금 (데릴리움, 메가사탄, 도그마, 비스트, 마더, 울트라 그리디어)
└캐릭터가 상기방에 존재하고, 현재 방이 클리어 상태라면 출력

설정해놓은 브금중 랜덤으로 재생
브금은 언제든지 추가 및 삭제될 수 있으니 그에 맞는 최적화 코드
루아에서 별도로 볼륨 수치 조절할 수 있는 기능은 없어도 됨 (원본 파일 자체 소리를 조정해가면서 내가 직접 할거임)

**Comment by pdom0327** [comment]
재생은 잘 되는데 방을 옮길 때 마다 원래 음악으로 돌아가네요. 차라리 외부 프로그램으로 만드는게 나을거 같습니다.

**Comment by iwt2hw** [comment]
해당 이슈의 경우 비트님에게 일단 부탁했음
외부프로그램 가능하냐고 물어봤더니 모드라 제작한다길래 일단 경과 두고 보기로...
