### ISSUE TITLE
보스모드 관련

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#82]
[bossroulette_v2_3043157956.zip](https://github.com/TeamHY/Astrobirth/files/13800839/bossroulette_v2_3043157956.zip)

마더 한글, 영문 명칭 전부 마더에서 위트니스로 변경

**Comment by pdom0327** [comment]
[bossroulette_witness.zip](https://github.com/TeamHY/Astrobirth/files/13814478/bossroulette_witness.zip)

**Comment by iwt2hw** [comment]
테스트 문제 없음
