### ISSUE TITLE
신규 아이템 : 학사학위(Bachelor's Degree)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#87]
-걸프 알약 + 스텟 관련 알약만 드랍되도록 변경됩니다
![Bachelor's Degree](https://github.com/TeamHY/Astrobirth/assets/28684443/54f4ea2a-58cc-4fdb-9011-31e12de31cd4)

**Comment by pdom0327** [comment]
1. 밴 시스템과 동일하게 (게임 당 13개의 알약만 존재 함. 밴 알약은 등장하지 않기 때문에 게임에는 이 보다 적은 종류의 알약만 생성 됨)
2. 13개 효과 중 걸프, 스탯 관련 아닌게 존재할 경우 동일 비중 완전 랜덤으로 재할당

어떤걸로 할까요?

**Comment by iwt2hw** [comment]
2
