### ISSUE TITLE
신규 아이템 : 핑크 와드(Pink Ward)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#88]
-설정된 몬스터들이 아군으로 취급됩니다 (사진 확인)
![KakaoTalk_20240109_170630786](https://github.com/TeamHY/Astrobirth/assets/28684443/64be7ff5-811e-44b6-92ed-155ced757ce1)
![KakaoTalk_20240109_170644599](https://github.com/TeamHY/Astrobirth/assets/28684443/0a6ccd13-38a7-4783-8f7f-cc6f95382259)
![KakaoTalk_20240109_170706726](https://github.com/TeamHY/Astrobirth/assets/28684443/f07e902a-4aa3-43ec-8a5c-a8071779a1c2)
![KakaoTalk_20240109_170745213](https://github.com/TeamHY/Astrobirth/assets/28684443/006a48ae-d0c2-4c5b-946a-07092af7cf1c)
![KakaoTalk_20240109_170808043](https://github.com/TeamHY/Astrobirth/assets/28684443/14df5ca8-7226-4d72-a1a4-61e9ccab1fe4)

![Pink Ward](https://github.com/TeamHY/Astrobirth/assets/28684443/8b7751bd-acdd-4917-af83-50cb2277a83a)

※※※※※※※※※※※※※※※※※※※※
-상기 매혹(아군) 효과는, 현재 핑크 와드 효과에서 "추가"적으로 적용되는 효과임
-레드 특수방 보여주는 위치는 구현하지 않아도 됨
-기존 핑크 와드가 가진, 일반 와드의 효과는 리뉴얼 하지않고, 그대로 유지

**Comment by pdom0327** [comment]
생각했던 방식으로 안 되네요. 다시 업데이트 하겠습니다.

**Comment by iwt2hw** [comment]
기존 효과 기각, 완전 리뉴얼 본문 내용 확인
