### ISSUE TITLE
신규 아이템 : 론고미니아드(Rhongomyniad)

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#90]
![Rhongomyniad](https://github.com/TeamHY/Astrobirth/assets/28684443/e790984f-27c2-4a15-9745-61ccc2e4b9d1)
- 기본 로직은 삼위일체와 동일함
- 스테이지 입장 시 소지한 아이템 1개 or 설정된 아이템 중 1개 이지선다 소환
- 소환되는 아이템은 클리너에 포함되어 있는 아이템들
- 단 론고미니아드의 경우 아이템 제거 효과가 발동되지 않음. (예: 삼위일체와 표리일체는 스테이지 진입 시 제거되지만 론고미니아드로 획득한 공격형 아이템은 제거되지 않음)
- 삼손의 기본 아이템이자 컨셉
- 획득 시 발동 되지 않아도 상관 없음

**Comment by pdom0327** [comment]
> - 스테이지 입장 시 소지한 아이템 1개 or 설정된 아이템 중 1개 이지선다 소환
> - 소환되는 아이템은 클리너에 포함되어 있는 아이템들

제가 이해한 효과는 위 두 줄이라서 구현 확인해보시고 수정사항 말씀해주세요!

**Comment by iwt2hw** [comment]
if EID then
    EID:addCollectible(Astro.Collectible.RHONGOMYNIAD, "스테이지를 넘어갈 때마다 소지된 아이템 중 하나를 제거합니다. 제거된 아이템과 " .. Astro.CleanerEIDString .. " 중 하나를 소환합니다. 하나를 선택하면 나머지는 사라집니다.", "론고미니아드")
end

설정된 아이템은 클리너에 있는 아이템들 (공격형 아이템) 의도된게 맞지만 별도로 내가 수기로 작성할 수 있게 변경
론고미니아드랑 클리너랑 완전히 배열을 동일 시 하지 않을 목적이기 때문

**Comment by pdom0327** [comment]
수정했습니다.
