### ISSUE TITLE
대결 모드 업적 관련

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Astrobirth#92]
-로스트로 마더 클리어 (Cygnus)
-로스트로 메가사탄 클리어 (Libra EX)
-로스트로 체스트 클리어 (Cancer EX)
-로스트로 다크룸 클리어 (Scorpio EX)

-챌린지 이름은 해금 아이템 명칭과 동일
-4개의 챌린지 모드 게임 시간 18분이 넘어갈 경우 캐릭터가 즉사
-해당 챌린지가 꺠져있는 상태가 아닐 경우 해당 아이템 배열되지 않는 시스템 추가

**Comment by pdom0327** [comment]
<img width="411" alt="image" src="https://github.com/TeamHY/Astrobirth/assets/12953393/61fa4bec-1638-4c6e-9125-792f8f06db7d">
콘솔창에 언락 여부 뜨도록 했습니다.
